package admin.sigmastock.sigmastock.Util;

import org.json.JSONException;
import org.json.JSONObject;

import java.util.HashMap;

/**
 * Created by HuyPD on 7/19/2016.
 */
public class Language
{
    public static HashMap<String, String> hashMap = null;

    public Language(String strJsonContent)
    {
        String strLang = "";
        try {
            JSONObject jsonObject = new JSONObject(strJsonContent);
            if(jsonObject.has("account"))
            {
                strLang = jsonObject.getJSONObject("account").get("language").toString();
            }
            if (strLang.compareToIgnoreCase("Vi")==0)
            {
                putdataVI();
            }
            else
            {
                putdataEN();
            }
        } catch (JSONException e) {
            e.printStackTrace();
        }

    }

    public void  putdataEN()
    {
        hashMap = new HashMap<>();
        hashMap.put("LOGIN_FAIL","Log in failed. Please try again later");
        hashMap.put("LBL_TICKET_LOWER","ticket");
        hashMap.put("LBL_TICKET","Ticket");
        hashMap.put("LBL_USER","User");
        hashMap.put("LBL_REQUESTER","Requester");
        hashMap.put("LBL_CREATED_TIME","Created time");
        hashMap.put("LBL_UPDATED_TIME","Updated time");
        hashMap.put("INVALID_PASSWORD","Invalid Username/Password");
        hashMap.put("LBL_ASSIGNEE","Assignee");
        hashMap.put("LBL_GROUP","Group");
        hashMap.put("LBL_TICKET_STATUS","Status");
        hashMap.put("LBL_TICKET_TYPE","Type");
        hashMap.put("LBL_TICKET_PRIORITY","Priority");
        hashMap.put("LBL_TICKET_SOURCE","Source");
        hashMap.put("LBL_TAGS","Tags");
        hashMap.put("LBL_DUE_DATE","Due Date");
        hashMap.put("LBL_TICKET_TYPE_DETAIL","Type detail");
        hashMap.put("LBL_TICKET_SUBJECT","Subject");
        hashMap.put("LBL_TICKET_DESCRIPTION","Description");
        hashMap.put("LBL_TICKET_PUBLIC_REPLY","Public reply");
        hashMap.put("LBL_TICKET_INTERNAL_NOTE","Internal Note");
        hashMap.put("LBL_TICKET_FACEBOOK_POST","Facebook Post");
        hashMap.put("LBL_TICKET_ATTACH _FILE","Attach file");
        hashMap.put("HINT_TICKET_DESCRIPTION_PUBLIC_REPLY","your comment will be sent to email address of the ticket requester (if existed)");
        hashMap.put("HINT_TICKET_DESCRIPTION_PUBLIC_REPLY_FB","your comment will create a comment on Facebook");
        hashMap.put("HINT_TICKET_DESCRIPTION_PUBLIC_REPLY_FBM","your comment will go to ticket requester's inbox on Facebook");
        hashMap.put("HINT_TICKET_DESCRIPTION_INTERNAL_NOTE","Note can only be seen by assignees");
        hashMap.put("HINT_TICKET_DESCRIPTION","your comment will be sent to ticket requester");
        hashMap.put("TICKET_STATUS_NEW","New");
        hashMap.put("TICKET_STATUS_OPEN","Open");
        hashMap.put("TICKET_STATUS_PENDING","Pending");
        hashMap.put("TICKET_STATUS_HOLD","Hold");
        hashMap.put("TICKET_STATUS_SOLVED","Solved");
        hashMap.put("TICKET_STATUS_CLOSED","Closed");
        hashMap.put("PHR_SEARCH_NAME_CONTACT","search name of contact info");
        hashMap.put("PHR_REQUESTER","search name of contact info");
        hashMap.put("PHR_CC","search name of contact info");
        hashMap.put("BTN_SUBMIT_TICKET","Submit as");

        hashMap.put("_comments","Ticket summary");
        hashMap.put("LBL_TICKET_SUMARY_VIEWS","Ticket Filters");
        hashMap.put("LBL_TICKET_SUMARY_NEXT_SLA_BREACH","SLA milestone");
        hashMap.put("LBL_TICKET_SUMARY_UNSOLVED_TICKET","Unsolved tickets");
        hashMap.put("LBL_TICKET_SUMARY_ALL_UNSOLVED_TICKET","All unsolved tickets");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_UNSOLVED_TICKET","Unsolved tickets in your group");
        hashMap.put("LBL_TICKET_SUMARY_UNASSIGNED_TICKET","Unassigned tickets");
        hashMap.put("LBL_TICKET_SUMARY_ALL_UNASSIGNED_TICKET","All unassigned tickets");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_UNASSIGNED_TICKET","Unassigned tickets in your group");
        hashMap.put("LBL_TICKET_SUMARY_PENDING_TICKET","Pending tickets");
        hashMap.put("LBL_TICKET_SUMARY_ALL_PENDING_TICKET","All pending tickets");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_PENDING_TICKET","Pending tickets in your group");
        hashMap.put("LBL_TICKET_SUMARY_OPEN_TICKET","Open tickets");
        hashMap.put("LBL_TICKET_SUMARY_ALL_OPEN_TICKET","All open tickets");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_OPEN_TICKET","Open tickets in your group");
        hashMap.put("LBL_TICKET_SUMARY_SOLVED_TICKET","Solved tickets");
        hashMap.put("LBL_TICKET_SUMARY_ALL_SOLVED_TICKET","All solved tickets");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_SOLVED_TICKET","Solved tickets in your group");
        hashMap.put("LBL_TICKET_SUMARY_CLOSED_TICKET","Closed tickets");
        hashMap.put("LBL_TICKET_SUMARY_ALL_CLOSED_TICKET","All closed tickets");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_CLOSED_TICKET","Closed tickets in your group");
        hashMap.put("LBL_TICKET_SUMARY_VOICE_TICKET","Voice tickets");
        hashMap.put("LBL_TICKET_SUMARY_ALL_VOICE_TICKET","All voice tickets");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_VOICE_TICKET","Voice tickets in your group");
        hashMap.put("LBL_TICKET_SUMARY_CHAT_TICKET","Chat tickets");
        hashMap.put("LBL_TICKET_SUMARY_ALL_CHAT_TICKET","All chat tickets");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_CHAT_TICKET","Chat tickets in your group");
        hashMap.put("LBL_TICKET_SUMARY_EMAIL_TICKET","Email tickets");
        hashMap.put("LBL_TICKET_SUMARY_ALL_EMAIL_TICKET","All email tickets");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_EMAIL_TICKET","Email tickets in your group");
        hashMap.put("LBL_TICKET_SUMARY_SMS_TICKET","SMS tickets");
        hashMap.put("LBL_TICKET_SUMARY_ALL_SMS_TICKET","All SMS tickets");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_SMS_TICKET","SMS tickets in your group");
        hashMap.put("LBL_TICKET_SUMARY_ALL_WEB_TICKET","All web tickets");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_WEB_TICKET","Web tickets in your group");
        hashMap.put("LBL_TICKET_SUMARY_WEB_TICKET","Web tickets");
        hashMap.put("LBL_TICKET_SUMARY_ALL_FACEBOOK_TICKET","All facebook tickets");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_FACEBOOK_TICKET","Facebook tickets in your group");
        hashMap.put("LBL_TICKET_SUMARY_FACEBOOK_TICKET","Facebook tickets");
        hashMap.put("LBL_TICKET_SUMARY_ALL_VOICEMAIL_TICKET","All voicemail tickets");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_VOICEMAIL_TICKET","Voicemail tickets in your group");
        hashMap.put("LBL_TICKET_SUMARY_VOICEMAIL_TICKET","Voicemail tickets");
        hashMap.put("LBL_TICKET_SUMARY_ALL_MISSEDCALL_TICKET","All missed call");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_MISSEDCALL_TICKET","Missed call in your group");
        hashMap.put("LBL_TICKET_SUMARY_MISSEDCALL_TICKET","Missed call");
        hashMap.put("LBL_TICKET_SUMARY_ALL_MISSEDCHAT_TICKET","All missed chat");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_MISSEDCHAT_TICKET","Missed chat in your group");
        hashMap.put("LBL_TICKET_SUMARY_MISSEDCHAT_TICKET","Missed chat");
        hashMap.put("LBL_TICKET_SUMARY_ALL_OFFLINECHAT_TICKET","All offline chat");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_OFFLINECHAT_TICKET","Offline chat in your group");
        hashMap.put("LBL_TICKET_SUMARY_OFFLINECHAT_TICKET","Offline chat");
        hashMap.put("LBL_TICKET_SUMARY_RECENTLY_24H_TICKET","Recently updated ticket");
        hashMap.put("LBL_TICKET_SUMARY_ALL_RECENTLY_24H_TICKET","All recently updated tickets");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_RECENTLY_24H_TICKET","Group recently updated tickets");
        hashMap.put("LBL_TICKET_SUMARY_NEW_REGISTER","New register");
        hashMap.put("ticket_status","Status");
        hashMap.put("assignee_username","Assignee");
        hashMap.put("requester_username","Requester");

        hashMap.put("_comments","Edit ticket summary");
        hashMap.put("LBL_EDIT_TICKET","ticket");
        hashMap.put("MESSAGE_DELETE_TICKET_SUCCESS","Deleted {{tickets}} ticket(s) successfully");
        hashMap.put("MESSAGE_DELETE_TICKET_FAIL","These tickets cannot be deleted");
        hashMap.put("MESSAGE_SOLVED_TICKET_SUCCESS","Solved {{tickets}} ticket(s) successfully");
        hashMap.put("MESSAGE_SOLVED_TICKET_FAIL","These tickets cannot be solved");
        hashMap.put("_comments","Contact summary");
        hashMap.put("LBL_CONTACT_SUMARY_VIEWS","Customer Filters");
        hashMap.put("LBL_CONTACT_SUMARY_CREATE_LESS_THAN_30","New customers (within the last 30 days)");
        hashMap.put("LBL_CONTACT_SUMARY_AGENTS_GROUP","List agents in group");
        hashMap.put("LBL_CONTACT_SUMARY_AGENTS","List agents");
        hashMap.put("LBL_CONTACT_LOWER","Customer");
        hashMap.put("LBL_CONTACT_NAME","Name");
        hashMap.put("LBL_CONTACT_EMAIL","Email");
        hashMap.put("LBL_CONTACT_PHONE_NUMBER","Phone number");
        hashMap.put("LBL_CONTACT_ORGANIZATION","Organization");
        hashMap.put("LBL_CONTACT_ORGANIZATION_DOMAIN","Domain address");
        hashMap.put("LBL_CONTACT_AGENT_ID","IP Phone");

        hashMap.put("_comments","Contact detail");
        hashMap.put("LBL_PHONE","Phone number");
        hashMap.put("LBL_EMAIL","Email");
        hashMap.put("LBL_FACEBOOK","Facebook");
        hashMap.put("LBL_ROLE","Role");
        hashMap.put("LBL_COMMENTS","Comments");
        hashMap.put("COMMENTS_NOTE_ONLY_1","Notes only");
        hashMap.put("COMMENTS_NOTE_ONLY_0","Notes and replies");
        hashMap.put("LBL_GENDER","Gender");
        hashMap.put("LBL_MALE","Male");
        hashMap.put("LBL_FEMALE","Female");
        hashMap.put("LBL_OTHER_GENDER","Others");
        hashMap.put("LBL_ADDRESS","Address");
        hashMap.put("LBL_PRIMARY_EMAIL","Primary Email");
        hashMap.put("LBL_DETAILS","Additional details");
        hashMap.put("LBL_NOTES","Notes");
        hashMap.put("LBL_TAGS","Tags");
        hashMap.put("LBL_LANGUAGE","Language");
        hashMap.put("LBL_NEW_TICKET","Add new ticket");
        hashMap.put("LBL_DELETE_CONTACT","Delete");
        hashMap.put("LBL_MENU_ITEM_EMAIL_EDIT","Edit");
        hashMap.put("LBL_MENU_ITEM_EMAIL_SEND","Send email");
        hashMap.put("LBL_MENU_ITEM_EMAIL_REMOVE","Delete");
        hashMap.put("LBL_MENU_ITEM_PHONE_EDIT","Edit");
        hashMap.put("LBL_MENU_ITEM_OPEN_PAGE","Open Facebook page");
        hashMap.put("LBL_MENU_ITEM_PHONE_CALL","Call");
        hashMap.put("LBL_MENU_ITEM_PHONE_REMOVE","Delete");
        hashMap.put("LBL_MENU_ITEM_PHONE_SEND_SMS","Send SMS");
        hashMap.put("LBL_MENU_ITEM_FACEBOOK_EDIT","Edit");
        hashMap.put("LBL_MENU_ITEM_FACEBOOK_VIEW","Information");
        hashMap.put("LBL_MENU_ITEM_FACEBOOK_REMOVE","Delete");
        hashMap.put("LBL_CONTACT_DETAIL_ASSINGED_TICKET","Assigned ticket");
        hashMap.put("LBL_CONTACT_DETAIL_REQUESTED_TICKET","Requested ticket");
        hashMap.put("LBL_CONTACT_UPLOAD_PHOTO_DESCRIPTION","Upload a new Photo...");
        hashMap.put("LBL_CONTACT_NEW_CONTACT","Add new customer");
        hashMap.put("LBL_CONTACT_NEW_ORGANIZATION","Add new organization");
        hashMap.put("LBL_CONTACT_ORGANIZATION_NEW_NOTE","Enter domains without space (e.g: acme.com). Users from these domains will be added to the organization.");
        hashMap.put("MESSAGE_NEW_CONTACT_SUCCESS","Created {{contact}} successfully");
        hashMap.put("MESSAGE_NEW_CONTACT_FAIL","{{contact}} cannot be created at the moment");
        hashMap.put("MESSAGE_UPDATE_CONTACT_SUCCESS","Updated {{contact}} successfully");
        hashMap.put("MESSAGE_UPDATE_CONTACT_FAIL","{{contact}} cannot be updated at the moment");
        hashMap.put("MESSAGE_UPDATE_CONTACT_INVALID","Contact update content is invalid or has already existed");
        hashMap.put("MESSAGE_DELETE_CONTACT_SUCCESS","Deleted {{contact}} successfully");
        hashMap.put("MESSAGE_DELETE_CONTACT_FAIL","{{contact}} cannot be deleted at the moment");

        hashMap.put("_comments","Organization detail");
        hashMap.put("MESSAGE_NEW_ORGANIZATION_SUCCESS","Successfully created organization");
        hashMap.put("MESSAGE_NEW_ORGANIZATION_FAIL","Organization cannot be deleted at the moment");

        hashMap.put("_comments","Report");
        hashMap.put("OVERVIEW_REPORT","Overview");
        hashMap.put("OVERVIEW_REPORT_TICKETS_RECEIVED","Number of received tickets");
        hashMap.put("OVERVIEW_REPORT_TICKETS_STATUS","Ticket status");
        hashMap.put("OVERVIEW_REPORT_AVG_RESOLVE_TIME","Average ticket resolve time");
        hashMap.put("OVERVIEW_REPORT_TICKET_SOLVED_NUM","Solved ticket");
        hashMap.put("OVERVIEW_REPORT_SLA_RATE","SLA resolve rate");
        hashMap.put("OVERVIEW_REPORT_OUTBOUND","Outbound");
        hashMap.put("TICKET_REPORT","Ticket report");
        hashMap.put("TICKET_REPORT_SUMARY","General ticket report");
        hashMap.put("TICKET_REPORT_BY_CHANNEL","Tickets received via channels");
        hashMap.put("TICKET_REPORT_STATUS_PROCESSING","Ticket processing status");
        hashMap.put("TICKET_REPORT_STATUS_PROCESSING_SOLVED","Solved");
        hashMap.put("TICKET_REPORT_STATUS_PROCESSING_PENDING","Pending");
        hashMap.put("TICKET_REPORT_AVGTIME","Average time");
        hashMap.put("TICKET_REPORT_AVGTIME","Average time ");
        hashMap.put("TICKET_REPORT_ANSWER_COUNT","Number of ticket answers");
        hashMap.put("TICKET_REPORT_REOPEN","Number of tickets to reopen");
        hashMap.put("REPORT_SUM","Sum");
        hashMap.put("REPORT_AVG","Average");
        hashMap.put("TICKET_REPORT","Ticket report");
        hashMap.put("CHAT_REPORT","Chat report");
        hashMap.put("CHAT_REPORT_SUMARY","Chat report summary");
        hashMap.put("CHAT_REPORT_TOTAL","Customers' chat");
        hashMap.put("CHAT_REPORT_TOTAL_ANSWER","Chat answer");
        hashMap.put("CHAT_REPORT_TOTAL_MISS","Missed chat");
        hashMap.put("CHAT_REPORT_ANSWERING_TIME","Chat responding time");
        hashMap.put("CHAT_REPORT_WATTING_TIME","Chat waiting time");

        hashMap.put("VOICE_REPORT","Voice report");
        hashMap.put("VOICE_REPORT_SUMARY","General voice report");
        hashMap.put("VOICE_REPORT_TOTAL_CALL","Number of calls report");
        hashMap.put("VOICE_REPORT_TIME_CALL","Call time report");
        hashMap.put("EMAIL_REPORT","Email channel report");
        hashMap.put("OUTBOUND_REPORT","Outbound report");
        hashMap.put("OUTBOUND_REPORT_SUMARY","Outbound report");
        hashMap.put("OUTBOUND_REPORT_VOICE","Outgoing call");
        hashMap.put("OUTBOUND_REPORT_EMAIL","Outgoing email");
        hashMap.put("OUTBOUND_REPORT_SMS","Outgoing SMS");
        hashMap.put("AGENT_REPORT","Detailed report");
        hashMap.put("AGENT_REPORT_LIST","Report list");
        hashMap.put("AGENT_REPORT_SUB_REPORT_LIST","Details");
        hashMap.put("AGENT_REPORT_STATUS","Time and status report");
        hashMap.put("AGENT_REPORT_TICKET","Ticket report");
        hashMap.put("AGENT_REPORT_TICKET_NUM","Number of tickets received via channels");
        hashMap.put("AGENT_REPORT_AVG_FIRST_REPLY","Average first-reply time");
        hashMap.put("AGENT_REPORT_AVG_TICKET_SOLVED","Average ticket processing time");
        hashMap.put("AGENT_REPORT_TICKET_CURRENT_STATUS","Tickets processing status");
        hashMap.put("AGENT_REPORT_TICKET_TYPE","NUmber of tickets via ticket type");
        hashMap.put("AGENT_REPORT_TICKET_SLA_OK","Number of tickets with correct SLA");
        hashMap.put("AGENT_REPORT_TICKET_SLA_NOK","Number of tickets with incorrect SLA");
        hashMap.put("AGENT_REPORT_TICKET_REOPEN","Number of closed and reopened tickets");
        hashMap.put("AGENT_REPORT_VOICE","Voice report");
        hashMap.put("AGENT_REPORT_CHAT","Chat report");
        hashMap.put("AGENT_REPORT_OUTBOUND","Outbound report");
        hashMap.put("AGENT_REPORT_OUTBOUND_VOICE","Outgoing call report");
        hashMap.put("AGENT_REPORT_OUTBOUND_VOICE_TOTAL","Number of outgoing calls");
        hashMap.put("AGENT_REPORT_OUTBOUND_VOICE_MEET","Number of outgoing calls to customers");
        hashMap.put("AGENT_REPORT_OUTBOUND_VOICE_MISS","Number of outgoing call not to customers");
        hashMap.put("AGENT_REPORT_OUTBOUND_EMAIL_SMS","Outgoing email and SMS report");
        hashMap.put("AGENT_REPORT_OUTBOUND_EMAIL","Number of outgoing emails");
        hashMap.put("AGENT_REPORT_OUTBOUND_SMS","Number of outgoing SMS");
        hashMap.put("AGENT_REPORT_SUMARY","Detailed report");
        hashMap.put("AGENT_REPORT_STATUS_LOGIN","Number of login attempts");
        hashMap.put("AGENT_REPORT_STATUS_VOICE_A"," Online Voice channel");
        hashMap.put("AGENT_REPORT_STATUS_VOICE_NA","Offline voice channel");
        hashMap.put("AGENT_REPORT_STATUS_VOICE_NOANSWER","No Answer Voice channel");
        hashMap.put("AGENT_REPORT_STATUS_CHAT_A","Online chat channel");
        hashMap.put("AGENT_REPORT_STATUS_CHAT_NA","Offline chat channel");
        hashMap.put("AGENT_REPORT_STATUS_EMAIL_A","Email AVAILABLE");
        hashMap.put("AGENT_REPORT_STATUS_EMAIL_NA","Email NOT AVAILABLE");
        hashMap.put("AGENT_REPORT_STATUS_SMS_A","SMS AVAILABLE");
        hashMap.put("AGENT_REPORT_STATUS_SMS_NA","SMS NOT AVAILABLE");
        hashMap.put("AGENT_REPORT_STATUS_TICKET_A","Online receive tickets");
        hashMap.put("AGENT_REPORT_STATUS_TICKET_NA","Offline receive tickets");
        hashMap.put("AGENT_REPORT_TICKET_RESOLVE","Solved");
        hashMap.put("AGENT_REPORT_TICKET_NOT_RESOLVE","Pending");
        hashMap.put("AGENT_REPORT_PERCENTAGE","Rate(%)");
        hashMap.put("AGENT_REPORT_SLA_OK","Correct SLA");
        hashMap.put("AGENT_REPORT_SLA_NOK","Incorrect SLA");
        hashMap.put("AGENT_REPORT_FIRST_REPLY","First reply");
        hashMap.put("AGENT_REPORT_MULTI_REPLY","Multi-reply");
        hashMap.put("LBL_QUANTITY","Quantity");

        hashMap.put("FILTER_BY_AGENT","Choose Agent");
        hashMap.put("REPORT_BY","Report by …:");
        hashMap.put("REPORT_BY_SUBREPORT","Report:");
        hashMap.put("PERIOD_TIME","Time");
        hashMap.put("PERIOD_TIME_30","The last 30 days");
        hashMap.put("PERIOD_TIME_7","The last 7 days");
        hashMap.put("PERIOD_TIME_1","The last 24 hours");
        hashMap.put("PERIOD_TIME_CUSTOM","Options");
        hashMap.put("PERIOD_TIME_START","From");
        hashMap.put("PERIOD_TIME_END","To");
        hashMap.put("LBL_ALL","All");

        hashMap.put("_comments","Common");
        hashMap.put("BTN_SAVE","Save");
        hashMap.put("BTN_UPDATE","Update");
        hashMap.put("BTN_CANCEL","Cancel");
        hashMap.put("BTN_CLOSE","Close");
        hashMap.put("BTN_SEND","Send");
        hashMap.put("LBL_EDIT","Edit");
        hashMap.put("LBL_DELETE","Delete");
        hashMap.put("LBL_MARK_SPAM","Mark as spam");
        hashMap.put("LBL_CLEAR_SELECTION","Clear selection");
        hashMap.put("LBL_EXPORT_CSV","Export as CSV");
        hashMap.put("BTN_ADD_CONTACT","Add contact");
        hashMap.put("LBL_SELECT_ACTION","Select an action");
        hashMap.put("CONFIRM_REFRESH_PAGE","Refreshing page may affect your data. Do you want to continue?");
        hashMap.put("NOTIFY_BROWSER_INVALID","System does not support your current browser. Please update to a newer version!");
        hashMap.put("SEMD_HELP_CONTENT","Help request from domain: {{domain}}<br/><b>Content:</b><br/>");
        hashMap.put("VALIDATE_CHANGEPASS_TITLE","<h1>Change password error:</h1>");
        hashMap.put("VALIDATE_CHANGEPASS_OLDVALUE_NULL","<li>Old password cannot be blank</li>");
        hashMap.put("VALIDATE_CHANGEPASS_NEWVALUE_NULL","<li>New password cannot be blank</li>");
        hashMap.put("VALIDATE_CHANGEPASS_MORE_6_CHAR","<li>Password contains at least 6 characters</li>");
        hashMap.put("VALIDATE_CHANGEPASS_SAME_OLDVALUE","<li>New password cannot be the same as old password</li>");
        hashMap.put("VALIDATE_CHANGEPASS_NOT_MATCH","<li>Incorrect password confirmation</li>");
        hashMap.put("MESSAGE_CHANGEPASS_FAILURE","Changed password failed");
        hashMap.put("MESSAGE_CHANGEPASS_SUCCESS","Changed password successfully");
        hashMap.put("MESSAGE_CHANGEPASS_INVALID","Incorrect old password");
        hashMap.put("MESSAGE_VOICE_NOANSWER_MORE","You have rejected more calls than the maximum allowed number");
        hashMap.put("MESSAGE_VOICE_TRANSFER_SUCCESS","Call transferred successfully");
        hashMap.put("MESSAGE_VOICE_TRANSFER_FAILURE","Call transfer failed");
        hashMap.put("NOTIFY_VOICE_NEW_CALL","You need a new call");
        hashMap.put("NOTIFY_VOICE_NEW_CALL_SDT","Phone number:");

        hashMap.put("_comments","SearchAll");
        hashMap.put("LBL_SEARCH_BY","Search: ");
        hashMap.put("LBL_ADVANCED_SEARCH","Advanced search");

        hashMap.put("LBL_TICKET_CREATED","Ticket #{{ticketNo}} has been created");
        hashMap.put("LBL_TICKET_UPDATED","Ticket #{{ticketNo}} has been updated");
        hashMap.put("INVALID_NUMBER","Invalid phone number!");

        hashMap.put("_comments","Entity");
        hashMap.put("ENTITY_VOICE","ENTITY_VOICE");
        hashMap.put("ENTITY_CHAT","ENTITY_CHAT");

        hashMap.put("TOTAL_SIMPLE","Total");
        hashMap.put("PENDING_SIMPLE","Pending");
        hashMap.put("SOLVED_SIMPLE","Solved");
        hashMap.put("TICKET_CHANNEL","Channel");
        hashMap.put("TICKET_TOTAL","Total");
        hashMap.put("TICKET_PENDING","Pending tickets");
        hashMap.put("TICKET_SOLVED","Solved tickets");
        hashMap.put("TICKET_UNSOLVED","Unsoved tickets");
        hashMap.put("AVG_RESPONSE","Average respond time (minute)");
        hashMap.put("AVG_CUSTOMER_REPLY","Average number of customer reply to ticket");
        hashMap.put("AVG_ANSWER_TICKET","Average number of agent reply to ticket");
        hashMap.put("AVG_FIRST_REPLY","Average time of first reply");
        hashMap.put("AVG_FIRST_REPLY_MIN"," Average time of first reply (minute)");
        hashMap.put("AVG_TICKET_SOLVED","Average time of closing ticket");
        hashMap.put("TOTAL_CHAT","Customers' total number of chat");
        hashMap.put("TOTAL_ANSWER_CHAT","Total number of chat answers");
        hashMap.put("TOTAL_MISS_CHAT","Total number of missed chat");
        hashMap.put("AVG_ANSWER_CHAT","Average time to answer a chat");
        hashMap.put("AVG_WAIT_CHAT","Average wait time for a chat");
        hashMap.put("REOPEN_TICKET","Number of closed tickets to be reopened");
        hashMap.put("NO_DATA_SHOW","No data is shown");
        hashMap.put("TOTAL_CALL","Total number of customers' calls");
        hashMap.put("TOTAL_MEET","Total number of answered calls");
        hashMap.put("TOTAL_MISS","Total number of missed calls");
        hashMap.put("TOTAL_MISS_BY_CUSTOMER","Total number of missed calls by customers");
        hashMap.put("TOTAL_MISS_BY_AGENT"," Total number of missed calls by agents");
        hashMap.put("TOTAL_MISS_BY_SYSTEM"," Total number of missed calls by system");
        hashMap.put("AVG_HOLD","Average hold time");
        hashMap.put("AVG_TALK","Average talk time");
        hashMap.put("AVG_WAIT","Average wait time");

        hashMap.put("LBL_SOLVED_WEB","Solved Web");
        hashMap.put("LBL_PENDING_WEB","Pending Web");
        hashMap.put("LBL_SOLVED_VOICE","Solved Voice");
        hashMap.put("LBL_PENDING_VOICE","Pending Voice");
        hashMap.put("LBL_SOLVED_CHAT","Solved Chat");
        hashMap.put("LBL_PENDING_CHAT","Pending Chat");
        hashMap.put("LBL_SOLVED_EMAIL","Solved Email");
        hashMap.put("LBL_PENDING_EMAIL","Pending Email");
        hashMap.put("LBL_SOLVED_VOICEMAIL","Solved Voicemail");
        hashMap.put("LBL_PENDING_VOICEMAIL","Pending Voicemail");
        hashMap.put("LBL_SOLVED_FACEBOOK","Solved Facebook");
        hashMap.put("LBL_PENDING_FACEBOOK","Pending Facebook");
        hashMap.put("LBL_TOTAL_CALLOUT","Total number of outgoing calls");
        hashMap.put("LBL_TOTAL_CALLOUT_OK","Total number of outgoing calls to customers");
        hashMap.put("LBL_TOTAL_CALLOUT_MISS","Total number of outgoing calls not to customers");
        hashMap.put("LBL_TOTAL_SENDOUT_EMAIL","Total number of outgoing emails");
        hashMap.put("LBL_TOTAL_SENDOUT_SMS","Total number of outgoing SMS");


        hashMap.put("UNSAVED_SMS_MESSAGE","You are composing 1 SMS. Do you want to reset data?");
        hashMap.put("UNSAVED_EMAIL_MESSAGE","You are composing 1 email. Do you want to reset data?");

        hashMap.put("_comment","AnhNT206");
        hashMap.put("LBL_ADD","Add");
        hashMap.put("LBL_ADD_NEW","Add new...");
        hashMap.put("LBL_SEARCH","Search");
        hashMap.put("LBL_RECENTLY_UPDATED_TICKETS","Recently updated tickets...");
        hashMap.put("LBL_VIEW_PROFILE","View profile page");
        hashMap.put("LBL_SIGN_OUT","Sign out");
        hashMap.put("TICKET_TYPE_QUESTION","Question");
        hashMap.put("TICKET_TYPE_PROBLEM","Problem");
        hashMap.put("TICKET_TYPE_TASK","Task");
        hashMap.put("-","-");

        hashMap.put("LBL_MONITORING","Monitor");
        hashMap.put("LBL_MONITORING_VOICE","Voice");
        hashMap.put("LBL_MONITORING_CHAT","Chat");
        hashMap.put("LBL_MONITORING_AGENT","Agent");
        hashMap.put("LBL_AGENT_STATUS_AVAILABLE","Available");
        hashMap.put("LBL_AGENT_STATUS_NOT_AVAILABLE","Not Available");
        hashMap.put("LBL_QUEUE","Queue");
        hashMap.put("LBL_MONITORING_CURRENT_ACTIVITY","Current activity");
        hashMap.put("LBL_MONITORING_ACTIVITY","Activity today");
        hashMap.put("LBL_MONITORING_WATING_CALL","Waiting call");
        hashMap.put("LBL_MONITORING_ANSWERING_CALL","Answering call");
        hashMap.put("LBL_MONITORING_TOTAL_CALL","Total number of calls");
        hashMap.put("LBL_MONITORING_TOTAL_AGENT","Number of agents signing in");
        hashMap.put("LBL_MONITORING_TOTAL_ONLINE_AGENT","Number of online agent");
        hashMap.put("LBL_MONITORING_AVERAGE_WAIT_TIME","Average wait time");
        hashMap.put("LBL_MONITORING_RESPONSE_RATIO","Call response rate");
        hashMap.put("LBL_MONITORING_TOTAL_AVERAGE_CALLS","Avarge number of calls of an agent");
        hashMap.put("LBL_MONITORING_ANSWER_TIME_PER_AGENT","Average answering time of an agent");
        hashMap.put("LBL_MONITORING_ANSWER_TIME_PER_CALL","Average answering time per call");
        hashMap.put("LBL_MONITORING_HOLD_TIME","Total number of calls placed on hold");
        hashMap.put("LBL_MONITORING_HOLD_AVERAGE_TIME","Average hold time");
        hashMap.put("LBL_MONITORING_MISS_CALL","Total number of missed calls");
        hashMap.put("LBL_MONITORING_REJECT_CALL","Total number of rejected calls");

        hashMap.put("LBL_MONITORING_WATING_CHAT","Number of waiting chats");
        hashMap.put("LBL_MONITORING_ANSWERING_CHAT","Number of chats which are being answered");
        hashMap.put("LBL_MONITORING_TOTAL_AGENT_CHAT","Number of agents signing in");
        hashMap.put("LBL_MONITORING_TOTAL_ONLINE_AGENT_CHAT","Number of available agent ");
        hashMap.put("LBL_MONITORING_TOTAL_CHAT","Total number of chats");
        hashMap.put("LBL_MONITORING_TOTAL_ANSWERED_CHAT","Number of answered chats");
        hashMap.put("LBL_MONITORING_MISS_CHAT","Number of missed chats");
        hashMap.put("LBL_MONITORING_MISS_CHAT_NO_AGENT","Number of missed chats because of no available agent");
        hashMap.put("LBL_MONITORING_CHAT_WAIT_TIME","Average wait time");
        hashMap.put("LBL_MONITORING_CHAT_ANSWER_TIME","Average answer time");
        hashMap.put("LBL_AGENT_ACTIVITY","Agent daily activity");
        hashMap.put("LBL_AGENT_CHAT_ACTIVITY","Agent daily chat activity");
        hashMap.put("LBL_USERNAME","Agent name");
        hashMap.put("LBL_AGENT_STATUS","Status");
        hashMap.put("LBL_TIME_AVAILABLE","Online time");
        hashMap.put("LBL_CALLS_ACCEPT","Number of received calls");
        hashMap.put("LBL_CALLS_DENY","Number of refected calls");
        hashMap.put("LBL_AVERAGE_ANSWER_TIME","Average answer time");
        hashMap.put("LBL_TOTAL_ANSWER_TIME","Total answer time");
        hashMap.put("LBL_NUMBER_ANSWER_CHAT","Number of received chats");
        hashMap.put("LBL_NUMBER_MISS_CHAT","Number of missed chats");


        hashMap.put("_comments","Report");
        hashMap.put("LBL_REPORT","Report");

        hashMap.put("SUBJECT_NOT_EMPTY","Subject cannot be blank");
        hashMap.put("COMMENT_NOT_EMPTY"," Description cannot be blank ");
        hashMap.put("ENABLE_VOICE_CONFIRM","Activating voice function may affect the call. Do you want to continue?");
        hashMap.put("LBL_INCOMING_CALL","Incoming call");
        hashMap.put("LBL_OUTGOING_CALL","Outgoing call");
        hashMap.put("BTN_CALL","Call");
        hashMap.put("BTN_CALLING","Connecting to agent...");
        hashMap.put("LBL_CURRENTLY_OFFLINE","You are offline");
        hashMap.put("LBL_NO_INCOMING_CALLS","There is no incoming call");
        hashMap.put("LBL_MISSED_CALL","Missed calls");
        hashMap.put("LBL_TICKET_FOR_CALL","Ticket for calls:");
        hashMap.put("BTN_DECLINE_CALL","Decline");
        hashMap.put("BTN_ACCEPT_CALL","Accept");
        hashMap.put("BTN_HANG_UP","Hang up");
        hashMap.put("BTN_TRANSFER","Transfer");
        hashMap.put("BTN_ENABLE_VOICE","Enable Voice");
        hashMap.put("LBL_ENABLE_VOICE_TO_CALL","Please enable voice to call to customer");
        hashMap.put("LBL_TRANSFER_REQUEST","Transfer request");
        hashMap.put("LBL_TRANSFER_MESSAGE","You are receiving call transfer request from");
        hashMap.put("LBL_TRANSFER_AGENT","Transfer call to another agent");
        hashMap.put("LBL_TRANSFER_PROF","Transfer call to phone number");
        hashMap.put("AGENT_LIST","Agent list");
        hashMap.put("PROF_LIST","Phone number list");
        hashMap.put("LBL_CONFIRMATION","Confimation");
        hashMap.put("LBL_CONFIRMATION_CHANGE_DEVICE","Changing receptive device requires system to refresh pages. Do you want to continue?");
        hashMap.put("LBL_NOTIFICATION","Notification");
        hashMap.put("LBL_VERSION","Version 1.1");
        hashMap.put("LBL_CHANGE_PWD","Change password");
        hashMap.put("LBL_CURRENT_PWD","Current password");
        hashMap.put("LBL_NEW_PWD","New password");
        hashMap.put("LBL_CONFIRM_PWD","Confirm new password");
        hashMap.put("BTN_CHANGE_PWD","Change");
        hashMap.put("LBL_VIA_BROWSER","Receive calls via browser");
        hashMap.put("LBL_VIA_SOFTPHONE","Receiving calls via IP Phone");
        hashMap.put("LBL_VIA_MOBILE","Transfer calls to the phone number: ");
        hashMap.put("LBL_VIA_NO_WEB","Offline mode (receiving calls via IP Phone/Mobile App)");
        hashMap.put("BTN_ENTER_NUMBER_CALLOUT","Enter callout phone number...");

        hashMap.put("ERROR_CALLOUT","Calling out is impossible when receiving call");
        hashMap.put("ERROR_CALLOUT_CONNECT","Connection failed. Please try again later");
        hashMap.put("IPCC_NOT_CONNECT_AGENT_ID","Connection to Agent failed");
        hashMap.put("IPCC_CUSTOMER_REJECT","Customer rejected the call");
        hashMap.put("IPCC_CUSTOMER_TIMEOUT","Customer did not pick up the call");
        hashMap.put("IPCC_CUSTOMER_NOT_CONNECT","Subscriber cannot be reached at the moment");
        hashMap.put("ERROR_CHANGE_DEVICE_TYPE","Changing receptive device failed. Please try again later/");
        hashMap.put("MAX_SIZE_UPLOAD","Attached file must not be larger than 15MB");
        hashMap.put("UPLOAD_ERROR","Uploading file failed");

        hashMap.put("IPCCERR0000","No calls found");
        hashMap.put("IPCCERR0001","Agent is busy at the moment");
        hashMap.put("IPCCERR0002","No agents found");
        hashMap.put("IPCCERR0003","Call is on hold or mute");
        hashMap.put("IPCCERR0006","No customers found");
        hashMap.put("IPCCERR0008","Call cannot be holad while ringing");
        hashMap.put("IPCCERR0009","Call cannot be mute while ringing ");

        hashMap.put("SUBMIT_TICKET_ERROR","Saving ticket failed. Please try again later.");
        hashMap.put("OPEN_TICKET_ERROR","Opening ticket failed.");
        hashMap.put("OPEN_CONTACT_ERROR","User information cannot be found");
        hashMap.put("LBL_CHANGE_REQUESTER","Change");
        hashMap.put("LBL_ATTACK_FILE","Attach file");
        hashMap.put("LBL_CLOSE_TAB","Close tab");
        hashMap.put("LBL_STAY_ON_TICKET","Stay on ticket");
        hashMap.put("LBL_NO_TICKET","No tickets found");
        hashMap.put("LBL_NO_CONTACT","No user information found");
        hashMap.put("LBL_VISITOR_PATH","Visitor Path");
        hashMap.put("LBL_ADD_NAME","Add name");
        hashMap.put("LBL_ADD_EMAIL","Add email");
        hashMap.put("LBL_UNDEFINED","Undefined ");
        hashMap.put("LBL_NAME_UNDEFINED","Undefined name");
        hashMap.put("LBL_EMAIL_UNDEFINED","Undefined email");
        hashMap.put("LBL_PHONE_UNDEFINED","Undefined phone number");
        hashMap.put("LBL_ADD_PHONE","Enter phone number");
        hashMap.put("LBL_LOCATION","Location");
        hashMap.put("LBL_BROWSER","Browser");
        hashMap.put("LBL_PLATFORM","Platform");
        hashMap.put("LBL_DEVICE","Devide");
        hashMap.put("LBL_IP_ADDRESS","IP address");
        hashMap.put("LBL_USER_AGENT","User Agent");
        hashMap.put("LBL_SEND_EMAIL","Send reply email for ticket:");
        hashMap.put("LBL_SEND_SMS","Send reply SMS for ticket:");
        hashMap.put("LBL_SEND","Send");
        hashMap.put("LBL_SUBJECT","Subject");
        hashMap.put("LBL_MESSAGE","Message");
        hashMap.put("LBL_SOLVED","Solved");

        hashMap.put("_comments","RESPONDE_MESSAGE");
        hashMap.put("PERMISSION_DENIED_MESSAGE","You are not allowed to perform this");
        hashMap.put("SEND_SMS_OK_MESSAGE","Requested accepted");
        hashMap.put("LBL_CONFIRM_LOGOUT","You now can receive calls without signing in browser. After logging out, do you want to continue receiving calls?");
        hashMap.put("BTN_LOGOUT_WEB","Log out, continue receiving calls");
        hashMap.put("BTN_LOGOUT_ALL"," Log out, stop receiving calls ");
        hashMap.put("TITLE_REPLY_OUT","Contact with customers");
        hashMap.put("TITLE_CALLOUT","Call out to customers");
        hashMap.put("TITLE_SEND_EMAIL","Send email out to customers");
        hashMap.put("TITLE_SEND_SMS","Send SMS out to customers");
        hashMap.put("LBL_REASSIGN","Ressign to assignee");
        hashMap.put("LBL_REASSIGN_AGENT","Reassign to agent");
        hashMap.put("REASSIGN_NOT_SELECT_AGENT","You have not choosed assignee to reassign ticket");
        hashMap.put("MESSAGE_REASSIGN_TICKET_SUCCESS","Successfully reassigned ticket");
        hashMap.put("MESSAGE_REASSIGN_TICKET_FAIL","Reassigning ticket failed");
        hashMap.put("LBL_HIDE_COMMENT","Hide comment");
        hashMap.put("LBL_UNHIDE_COMMENT","Show comment");
        hashMap.put("LBL_REMOVE_COMMENT","Delete comment");
        hashMap.put("LBL_HIDED","Hidden comment");
        hashMap.put("LBL_DELETED","Deleted comment");
        hashMap.put("LBL_VIEW_EMAIL","View email");
        hashMap.put("LBL_SYSTEM_ERROR","System error occurred. Please try again later.");
        hashMap.put("LBL_UNHIDE_SUCCESS","Unhided comment successfully");
        hashMap.put("LBL_HIDE_SUCCESS","Hided comment successfully");
        hashMap.put("LBL_DELETE_SUCCESS","Deleted comment successfully");
        hashMap.put("LBL_CAN_NOT_CHANGE_CALL_STATUS","You cannot change call status into offline when you are in offline mode");
        hashMap.put("LBL_HELP","Contact Caresoft support");
        hashMap.put("LBL_ISSUE_TYPE","Type");
        hashMap.put("LBL_CONTENT","Message");
        hashMap.put("LBL_ATTACK_FILE_HELP","Attach file");
        hashMap.put("FACEBOOK_ATTACK_FILE_ERROR","Facebook allows one attack file only");
        hashMap.put("SEND_HELP_OK","Sent message successfully. We will contact you as soon as possible");

        hashMap.put("_comments","CHAT");
        hashMap.put("LBL_CHAT_TITLE","CS Chat");
        hashMap.put("LBL_CHAT_RECONNECT_TO_CHAT","Reconnect to chat");
        hashMap.put("LBL_CHAT_RECONNECTING","Reconnecting...");
        hashMap.put("LBL_CHAT_LIST_CONVERSATION","Open Chats");
        hashMap.put("LBL_CHAT_STATUS_ONLINE","Online");
        hashMap.put("LBL_CHAT_STATUS_OFFLINE","Offline");
        hashMap.put("LBL_CHAT_AGENT_ONLINE","Online Agents");
        hashMap.put("LBL_CHAT_AGENT_STATUS_ONLINE","online");
        hashMap.put("LBL_CHAT_NO_REQUEST","No chat requests");
        hashMap.put("LBL_CHAT_ACCEPT_REQUEST","Accept {{chatRequest}} requests");
        hashMap.put("LBL_CHAT_CURRENT_CHAT","Chatting");
        hashMap.put("LBL_CHAT_HISTORY","Chat history");
        hashMap.put("LBL_CHAT_HISTORY_TIME","Conversation took place at {{time}}");
        hashMap.put("LBL_CHAT_HISTORY_RATING","Rate");
        hashMap.put("LBL_CHAT_HISTORY_RATING_0","-");
        hashMap.put("LBL_CHAT_HISTORY_RATING_1","Good");
        hashMap.put("LBL_CHAT_HISTORY_RATING_2","Bad");
        hashMap.put("LBL_CHAT_HISTORY_CUSTCOMMENT","Comments");
        hashMap.put("LBL_CHAT_VISITOR_INFO","Customer information");
        hashMap.put("BTN_CHAT_NEXT","Transfer chat");
        hashMap.put("LBL_CHAT_SENDING","Sending...");
        hashMap.put("LBL_CHAT_RESEND","Resend");
        hashMap.put("LBL_CHAT_SENDING_FAILED","Sending failed");
        hashMap.put("LBL_CHAT_YOU_SENT","You sent:");
        hashMap.put("LBL_CHAT_PARTNER_SENT","sent:");
        hashMap.put("LBL_VIEW_PREVIOUS_CHAT","View previous chat");
        hashMap.put("LBL_CHAT_REQUEST_RATING","Request for rating from customers:");
        hashMap.put("LBL_CHAT_NO_MATCHE_SHORTCUT_1","No matching shortcuts.");
        hashMap.put("LBL_CHAT_NO_MATCHE_SHORTCUT_2","Remove the slash to search the full shortcut messages.");
        hashMap.put("LBL_CHAT_UPLOADING","Uploading...");
        hashMap.put("LBL_CHAT_ATTACK","Attach");
        hashMap.put("LBL_CHAT_CUST_OFFLINE","Offline.");
        hashMap.put("LBL_CHAT_NO_CHAT_PRE","No chat history");
        hashMap.put("LBL_CHAT_AGENT","Agent");
        hashMap.put("LBL_CHAT_TIME","Time");
        hashMap.put("LBL_CHAT_RECEIVE_TIME","Received time:");
        hashMap.put("LBL_CHAT_FACEBOOKID","Personal page");
        hashMap.put("LBL_CHAT_FACEBOOK_PAGE","Page:");
        hashMap.put("LBL_CHAT_TRANSFER_TO_AGENT","Transfer chat to another agent");
        hashMap.put("LBL_CHAT_TRANSFER_AGENT_NAME","Agent name");
        hashMap.put("PHR_CHAT_TRANSFER_AGENT_NAME_INPUT","Enter agent name and choose from the list");
        hashMap.put("LBL_CHAT_TRANSFER_NO_AGENT","No agent was chosen to transfer chat");
        hashMap.put("BTN_CHAT_TRANSFER","Transfer");
        hashMap.put("BTN_CHAT_TRANSFER_CANCEL","Cancel");
        hashMap.put("PHR_CHAT_NO_CHAT","You have no open chats now.");
        hashMap.put("PHR_CHAT_LIST_CHAT","Chat served by you will appear here.");
        hashMap.put("LBL_CHAT_TICKET_SUBJECT","Chat with user: ");
        hashMap.put("LBL_CHAT_TICKET_COMMENT_USERNAME","Username: ");
        hashMap.put("LBL_CHAT_TICKET_COMMENT_EMAIL","Email: ");
        hashMap.put("LBL_CHAT_TICKET_COMMENT_PHONE","Phone number: ");
        hashMap.put("LBL_CHAT_TICKET_COMMENT_STARTTIME","<p>Chat start time ");
        hashMap.put("LBL_CHAT_CONTENT_LEFT"," left chat");
        hashMap.put("LBL_CHAT_CONTENT_JOIN"," joined chat");
        hashMap.put("MESSAGE_CHAT_TRANSFER_AGENT_BUSY"," is busy");
        hashMap.put("MESSAGE_CHAT_TRANSFER_AGENT_NOTFOUND","No agents found");
        hashMap.put("MESSAGE_CHAT_TRANSFER_UNABLE","Chat cannot be transferred to agent ");
        hashMap.put("MESSAGE_CHAT_TRANSFER_CANT","This chat cannot be transferred");
        hashMap.put("MESSAGE_CHAT_TRANSFER_AGENT_ACCEPTED"," accepted chat transfer request");
        hashMap.put("MESSAGE_CHAT_TRANSFER_AGENT_DENIED"," rejected chat transfer request");
        hashMap.put("MESSAGE_CHAT_TRANSFER_CONV_ENDED","No chats found!");
        hashMap.put("MESSAGE_CHAT_TRANSFER_CONV_NOT_FOUND","Agent cannot be found!");
        hashMap.put("LBL_CHAT_NEW_REQUEST","You have new chat request");
        hashMap.put("LBL_CHAT_SERVICE","Service: ");
        hashMap.put("LBL_CHAT_NEW_TRANSFER_REQUEST"," You have new chat transfer request");
        hashMap.put("LBL_CHAT_TRANSFER_AGENT","Transfer agent: ");
        hashMap.put("LBL_CHAT_NEW_MESSAGE","New messages from ");

        hashMap.put("_comments","EMAIL");
        hashMap.put("LBL_EMAIL_TITLE","CS Email");

        hashMap.put("_comments","TICKET");
        hashMap.put("LBL_TICKET_STATUS_ONLINE","CS Ticket - Online");
        hashMap.put("LBL_TICKET_STATUS_OFFLINE","CS Ticket - Offline");

        hashMap.put("_comments","VOICE");
        hashMap.put("LBL_VOICE_TITLE","CS Voice");
        hashMap.put("LBL_VOICE_CALLOUT_BY_TICKET","Call out by ticket");
        hashMap.put("LBL_VOICE_MORE_USING_THIS_PHONE","(*) There are several users using this phone number");

        hashMap.put("_comments","SMS");
        hashMap.put("LBL_SMS_TITLE","CS SMS");

        hashMap.put("_comments","INDEX");
        hashMap.put("LBL_INDEX_LOST_CONNECTION","Connection error.");
        hashMap.put("LBL_INDEX_RECONNECT","System is trying to reconnect...");
        hashMap.put("LBL_INDEX_CLICK_HERE","Click here");
        hashMap.put("LBL_INDEX_TO_RECONNECT","to reconnect");
        hashMap.put("LBL_INDEX_ADMIN_CONFIG","Configuration ");
        hashMap.put("LBL_INDEX_ADMIN_CONFIG_AGENT","Agent");
        hashMap.put("LBL_INDEX_ADMIN_CONFIG_GROUP","Group");
        hashMap.put("LBL_INDEX_ADMIN_CONFIG_CUST","User");
        hashMap.put("LBL_INDEX_ADMIN_CONFIG_CRM","Link to CRM");
        hashMap.put("LBL_INDEX_ADMIN_SERVICE","Service");
        hashMap.put("LBL_INDEX_ADMIN_SERVICE_VOICE","Voice");
        hashMap.put("LBL_INDEX_ADMIN_SERVICE_CHAT","Chat");
        hashMap.put("LBL_INDEX_ADMIN_SERVICE_EMAIL","Email");
        hashMap.put("LBL_INDEX_ADMIN_SERVICE_FACEBOOK","Facebook");
        hashMap.put("LBL_INDEX_ADMIN_SERVICE_SMS","SMS");
        hashMap.put("BTN_INDEX_HELP","Help");

        hashMap.put("_comments","LOGIN");
        hashMap.put("LBL_LOGIN_TITLE","Signin with");
        hashMap.put("PHR_LOGIN_YOUR_EMAIL","Enter you email");
        hashMap.put("PHR_LOGIN_YOUR_PASSWORD","Password");
        hashMap.put("BTN_LOGIN","Login");
        hashMap.put("MESSAGE_LOGIN_INVALID","Username/Password is incorrect.");
        hashMap.put("MESSAGE_LOGIN_FAILURE","Login failed. Please try again later.");
        hashMap.put("MESSAGE_LOGIN_EXPIRE","Your account has expired. Please contact Caresoft Customer Care Department to continue using Caresoft.");
        hashMap.put("WARNING_EXPIRE_DATE","Your account will expire in the next {{day}} days. Please contact Caresoft Customer Care Department to extend your account");
        hashMap.put("WARNING_EXPIRE_DATE_TODAY","Your account will expire today. Please contact Caresoft Customer Care Department to extend your account");

        hashMap.put("_comments","END");

        hashMap.put("_comments","send out");
        hashMap.put("LBL_ERR_SEND_MAIL_HEADER","<h1>Sending email error:</h1><ul>");
        hashMap.put("LBL_ERR_SEND_SMS_HEADER","<h1>Sending SMS error:</h1><ul>");
        hashMap.put("LBL_ERR_INVALID_EMAIL_TO","<li>Invalid email format</li>");
        hashMap.put("LBL_ERR_EMPTY_TITLE","<li>Title cannot be blank</li>");
        hashMap.put("LBL_ERR_EMPTY_CONTENT","<li>Content cannot be black</li>");

        hashMap.put("LBL_SEND_INBOX_FROM_COMMENT","Send Inbox from comment");
        hashMap.put("LBL_SEND_INBOX","Send Inbox");
        hashMap.put("LBL_SEND_OTT","Send Message to OTT App");
        hashMap.put("LBL_OTT_SERVICE","OTT Services");
        hashMap.put("LBL_EMPTY_MESSAGE","Message cannot be blank");
        hashMap.put("LBL_SEND_INBOX_SUCCESS","Send message successfully");
        hashMap.put("LBL_NOT_CHOOSE_PAGE","No chosen Page");
        hashMap.put("LBL_NOT_CHOOSE_SERVICE","No chosen Service");
        hashMap.put("LBL_MENU_ITEM_ADD_BLACKLIST","Add to Blacklist");
        hashMap.put("LBL_MENU_ITEM_REMOVE_BLACKLIST","Remove from Blacklist");
        hashMap.put("MESSAGE_ADD_BLACKLIST_SUCCESS","Add {{phone}} to Blacklist successfully");
        hashMap.put("MESSAGE_ADD_BLACKLIST_FAIL","Add {{phone}} to Blacklist failed");
        hashMap.put("MESSAGE_REMOVE_BLACKLIST_SUCCESS","Remove {{phone}} from Blacklist successfully");
        hashMap.put("MESSAGE_REMOVE_BLACKLIST_FAIL","Remove {{phone}} from Blacklist failed");

        hashMap.put("MESSAGE_SEND_EMAIL_FAIL","Failed to send Email. Please try again later!");
        hashMap.put("MESSAGE_SEND_SMS_FAIL","Failed to send SMS. Please try again later!");
        hashMap.put("MESSAGE_SEND_HELP_FAIL","Failed to send Help request. Please try again later!");
        hashMap.put("LBL_SENDING","Sending...");

        hashMap.put("LBL_AZ_USER","OTT ID");
        hashMap.put("LBL_CALL_TO_AZ","Call");
        hashMap.put("LBL_MESSAGE_TO_AZ","Send message");

        hashMap.put("LBL_TICKET_SOURCE_VOICE","Voice");
        hashMap.put("LBL_TICKET_SOURCE_CHAT","Chat");
        hashMap.put("LBL_TICKET_SOURCE_WEB","Web");
        hashMap.put("LBL_TICKET_SOURCE_EMAIL","Email");
        hashMap.put("LBL_TICKET_SOURCE_FACEBOOK","Facebook");
        hashMap.put("LBL_TICKET_SOURCE_VOICEMAIL","Voicemail");
        hashMap.put("LBL_TICKET_TYPE_OTHER","Other");

        hashMap.put("LBL_FORGET_PASSWORD","Forget password");
        hashMap.put("BTN_RESET_PASSWORD","Submit");
        hashMap.put("LBL_RESET_GUIDE_1","To reset your password for");
        hashMap.put("LBL_RESET_GUIDE_2","); enter your email address and we'll send you an email with instructions.");
        hashMap.put("LBL_CHANGE_PASSWORD_SUCCESS","Reset password successfully. Please check email to get your new password");
        hashMap.put("LBL_EMAIL_CHANGE_PWD_NOT_FOUND","This email is not belong to any agents in this account");

        hashMap.put("LBL_FACEBOOK_TITLE","CS Facebook");
        hashMap.put("LBL_REPLY_MESSAGE","Reply Message");
        hashMap.put("LBL_CHAT_UPLOAD_ERR_EXTENSION","You can only send image");
        hashMap.put("LBL_NOT_CHOOSE_FB_CONV","You are not choosing any conversations");
        hashMap.put("LBL_OPEN_IN_TICKET","Open ticket");
        hashMap.put("LBL_OPEN_IN_FACEBOOK","Open Facebook");
        hashMap.put("LBL_SHOW_COMMENT","Hide comment");
        hashMap.put("LBL_DELETE_COMMENT","Delete comment");
        hashMap.put("LBL_SEND_PRIVATE_MESSAGE","Send private message");
        hashMap.put("LBL_OPEN_CS_CONTACT","Open User info");
        hashMap.put("LBL_CLOSE_TICKET","Close ticket");
        hashMap.put("LBL_FB_NEW_REQUEST","You have new Facebook request");
        hashMap.put("LBL_FB_USER","Requester: ");
        hashMap.put("LBL_NO_FB_CONV","You do not have any conversations");


    }

    public void  putdataVI()
    {
        hashMap = new HashMap<>();
        hashMap.put("INVALID_PASSWORD","Tên đăng nhập/mật khẩu không chính xác.");
        hashMap.put("LOGIN_FAIL","Đăng nhập không thành công. Thử lại sau");
        hashMap.put("LBL_TICKET_LOWER","phiếu ghi");
        hashMap.put("LBL_TICKET","Phiếu ghi");
        hashMap.put("LBL_USER","Người dùng");
        hashMap.put("LBL_REQUESTER","Người yêu cầu");
        hashMap.put("LBL_CREATED_TIME","Thời điểm tạo");
        hashMap.put("LBL_UPDATED_TIME","Thời điểm cập nhật");
        hashMap.put("LBL_ASSIGNEE","Chuyên viên");
        hashMap.put("LBL_GROUP","Bộ phận");
        hashMap.put("LBL_TICKET_STATUS","Trạng thái");
        hashMap.put("LBL_TICKET_TYPE","Phân loại");
        hashMap.put("LBL_TICKET_PRIORITY","Ưu tiên");
        hashMap.put("LBL_TICKET_SOURCE","Nguồn");
        hashMap.put("LBL_TAGS","Tags");
        hashMap.put("LBL_DUE_DATE","Thời hạn xử lý");
        hashMap.put("LBL_TICKET_TYPE_DETAIL","Phân loại chi tiết");
        hashMap.put("LBL_TICKET_SUBJECT","Chủ đề");
        hashMap.put("LBL_TICKET_DESCRIPTION","Mô tả");
        hashMap.put("LBL_TICKET_PUBLIC_REPLY","Phản hồi");
        hashMap.put("LBL_TICKET_INTERNAL_NOTE","Ghi chú");
        hashMap.put("LBL_TICKET_FACEBOOK_POST","(Bài đăng trên Facebook)");
        hashMap.put("LBL_TICKET_ATTACK_FILE","Đính kèm file");
        hashMap.put("HINT_TICKET_DESCRIPTION_PUBLIC_REPLY","Phản hồi sẽ được gửi đến email của người yêu cầu phiếu ghi (Nếu có)");
        hashMap.put("HINT_TICKET_DESCRIPTION_PUBLIC_REPLY_FB","Phản hồi sẽ trở thành bình luận trên Facebook");
        hashMap.put("HINT_TICKET_DESCRIPTION_PUBLIC_REPLY_FBM","Phản hồi sẽ được chuyển đến Inbox (Facebook) của người yêu cầu phiếu ghi");
        hashMap.put("HINT_TICKET_DESCRIPTION_INTERNAL_NOTE","Ghi chú chỉ được thấy bởi chuyên viên");
        hashMap.put("HINT_TICKET_DESCRIPTION","Mô tả sẽ được gửi tới người yêu cầu phiếu ghi");
        hashMap.put("TICKET_STATUS_NEW","New");
        hashMap.put("TICKET_STATUS_OPEN","Open");
        hashMap.put("TICKET_STATUS_PENDING","Pending");
        hashMap.put("TICKET_STATUS_HOLD","Hold");
        hashMap.put("TICKET_STATUS_SOLVED","Solved");
        hashMap.put("TICKET_STATUS_CLOSED","Closed");
        hashMap.put("PHR_SEARCH_NAME_CONTACT","tìm chuyên viên hoặc khách hàng");
        hashMap.put("PHR_REQUESTER","tìm chuyên viên hoặc khách hàng");
        hashMap.put("PHR_CC","tìm chuyên viên hoặc khách hàng");
        hashMap.put("BTN_SUBMIT_TICKET","Cập nhật thành");
        hashMap.put("_comments","Ticket summary");
        hashMap.put("LBL_TICKET_SUMARY_VIEWS","Danh sách phiếu ghi");
        hashMap.put("LBL_TICKET_SUMARY_NEXT_SLA_BREACH","Mốc SLA");
        hashMap.put("LBL_TICKET_SUMARY_UNSOLVED_TICKET","Phiếu ghi chưa giải quyết");
        hashMap.put("LBL_TICKET_SUMARY_ALL_UNSOLVED_TICKET","Phiếu ghi chưa giải quyết (tất cả)");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_UNSOLVED_TICKET","Phiếu ghi chưa giải quyết (nhóm)");
        hashMap.put("LBL_TICKET_SUMARY_UNASSIGNED_TICKET","Phiếu ghi chưa gán");
        hashMap.put("LBL_TICKET_SUMARY_ALL_UNASSIGNED_TICKET","Phiếu ghi chưa gán (tất cả)");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_UNASSIGNED_TICKET","Phiếu ghi chưa gán (nhóm)");
        hashMap.put("LBL_TICKET_SUMARY_PENDING_TICKET","Phiếu ghi đang tạm dừng");
        hashMap.put("LBL_TICKET_SUMARY_ALL_PENDING_TICKET","Phiếu ghi đang tạm dừng (tất cả)");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_PENDING_TICKET","Phiếu ghi đang tạm dừng (nhóm)");
        hashMap.put("LBL_TICKET_SUMARY_OPEN_TICKET","Phiếu ghi đang mở");
        hashMap.put("LBL_TICKET_SUMARY_ALL_OPEN_TICKET","Phiếu ghi đang mở (tất cả)");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_OPEN_TICKET","Phiếu ghi đang mở (nhóm)");
        hashMap.put("LBL_TICKET_SUMARY_SOLVED_TICKET","Phiếu ghi đã giải quyết");
        hashMap.put("LBL_TICKET_SUMARY_ALL_SOLVED_TICKET","Phiếu ghi đã giải quyết (tất cả)");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_SOLVED_TICKET","Phiếu ghi đã giải quyết (nhóm)");
        hashMap.put("LBL_TICKET_SUMARY_CLOSED_TICKET","Phiếu ghi đã đóng");
        hashMap.put("LBL_TICKET_SUMARY_ALL_CLOSED_TICKET","Phiếu ghi đã đóng (tất cả)");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_CLOSED_TICKET","Phiếu ghi đã đóng (nhóm)");
        hashMap.put("LBL_TICKET_SUMARY_VOICE_TICKET","Phiếu ghi từ kênh thoại");
        hashMap.put("LBL_TICKET_SUMARY_ALL_VOICE_TICKET","Phiếu ghi từ kênh thoại (tất cả)");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_VOICE_TICKET","Phiếu ghi từ kênh thoại (nhóm)");
        hashMap.put("LBL_TICKET_SUMARY_CHAT_TICKET","Phiếu ghi từ kênh chat");
        hashMap.put("LBL_TICKET_SUMARY_ALL_CHAT_TICKET","Phiếu ghi từ kênh chat (tất cả)");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_CHAT_TICKET","Phiếu ghi từ kênh chat (nhóm)");
        hashMap.put("LBL_TICKET_SUMARY_EMAIL_TICKET","Phiếu ghi từ kênh Email");
        hashMap.put("LBL_TICKET_SUMARY_ALL_EMAIL_TICKET","Phiếu ghi từ kênh Email (tất cả)");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_EMAIL_TICKET","Phiếu ghi từ kênh Email (nhóm)");
        hashMap.put("LBL_TICKET_SUMARY_SMS_TICKET","Phiếu ghi từ kênh SMS");
        hashMap.put("LBL_TICKET_SUMARY_ALL_SMS_TICKET","Phiếu ghi từ kênh SMS (tất cả)");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_SMS_TICKET","Phiếu ghi từ kênh SMS (nhóm)");
        hashMap.put("LBL_TICKET_SUMARY_ALL_WEB_TICKET","Phiếu ghi từ kênh WEB (tất cả)");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_WEB_TICKET","Phiếu ghi từ kênh WEB (nhóm)");
        hashMap.put("LBL_TICKET_SUMARY_WEB_TICKET","Phiếu ghi từ kênh WEB");
        hashMap.put("LBL_TICKET_SUMARY_ALL_FACEBOOK_TICKET","Phiếu ghi từ kênh Facebook (tất cả)");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_FACEBOOK_TICKET","Phiếu ghi từ kênh Facebook (nhóm)");
        hashMap.put("LBL_TICKET_SUMARY_FACEBOOK_TICKET","Phiếu ghi từ kênh Facebook");
        hashMap.put("LBL_TICKET_SUMARY_ALL_VOICEMAIL_TICKET","Phiếu ghi từ kênh Voicemail (tất cả)");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_VOICEMAIL_TICKET","Phiếu ghi từ kênh Voicemail (nhóm)");
        hashMap.put("LBL_TICKET_SUMARY_VOICEMAIL_TICKET","Phiếu ghi từ kênh Voicemail");
        hashMap.put("LBL_TICKET_SUMARY_ALL_MISSEDCALL_TICKET","Cuộc gọi nhỡ (tất cả)");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_MISSEDCALL_TICKET","Cuộc gọi nhỡ (nhóm)");
        hashMap.put("LBL_TICKET_SUMARY_MISSEDCALL_TICKET","Cuộc gọi nhỡ");
        hashMap.put("LBL_TICKET_SUMARY_ALL_MISSEDCHAT_TICKET","Chat nhỡ (tất cả)");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_MISSEDCHAT_TICKET","Chat nhỡ (nhóm)");
        hashMap.put("LBL_TICKET_SUMARY_MISSEDCHAT_TICKET","Chat nhỡ");
        hashMap.put("LBL_TICKET_SUMARY_ALL_OFFLINECHAT_TICKET","Chat offline (tất cả)");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_OFFLINECHAT_TICKET","Chat offline (nhóm)");
        hashMap.put("LBL_TICKET_SUMARY_OFFLINECHAT_TICKET","Chat offline");
        hashMap.put("LBL_TICKET_SUMARY_RECENTLY_24H_TICKET","Phiếu ghi cập nhật gần đây");
        hashMap.put("LBL_TICKET_SUMARY_ALL_RECENTLY_24H_TICKET","Phiếu ghi cập nhật gần đây (tất cả)");
        hashMap.put("LBL_TICKET_SUMARY_GROUP_RECENTLY_24H_TICKET","Phiếu ghi cập nhật gần đây (nhóm)");
        hashMap.put("LBL_TICKET_SUMARY_NEW_REGISTER","Khách hàng đăng ký mới");
        hashMap.put("ticket_status","Trạng thái");
        hashMap.put("assignee_username","Chuyên viên");
        hashMap.put("requester_username","Người yêu cầu");
        hashMap.put("_comments","Edit ticket summary");
        hashMap.put("LBL_EDIT_TICKET","phiếu ghi");
        hashMap.put("MESSAGE_DELETE_TICKET_SUCCESS","Đã xóa {{tickets}} phiếu ghi");
        hashMap.put("MESSAGE_DELETE_TICKET_FAIL","Không thể xóa những phiếu ghi này");
        hashMap.put("MESSAGE_SOLVED_TICKET_SUCCESS","Đã giải quyết {{tickets}} phiếu ghi");
        hashMap.put("MESSAGE_SOLVED_TICKET_FAIL","Không thể giải quyết những phiếu ghi này");
        hashMap.put("_comments","Contact summary");
        hashMap.put("LBL_CONTACT_SUMARY_VIEWS","Danh sách khách hàng");
        hashMap.put("LBL_CONTACT_SUMARY_CREATE_LESS_THAN_30","Khách hàng được tạo trong 30 ngày gần nhất");
        hashMap.put("LBL_CONTACT_SUMARY_AGENTS_GROUP","Danh sách chuyên viên trong nhóm");
        hashMap.put("LBL_CONTACT_SUMARY_AGENTS","Danh sách chuyên viên");
        hashMap.put("LBL_CONTACT_LOWER","khách hàng");
        hashMap.put("LBL_CONTACT_NAME","Tên");
        hashMap.put("LBL_CONTACT_EMAIL","Email");
        hashMap.put("LBL_CONTACT_PHONE_NUMBER","Số điện thoại");
        hashMap.put("LBL_CONTACT_ORGANIZATION","Cơ quan");
        hashMap.put("LBL_CONTACT_ORGANIZATION_DOMAIN","Địa chỉ tên miền");
        hashMap.put("LBL_CONTACT_AGENT_ID","IP Phone");
        hashMap.put("_comments","Contact detail");
        hashMap.put("LBL_PHONE","Số điện thoại");
        hashMap.put("LBL_EMAIL","Email");
        hashMap.put("LBL_FACEBOOK","Facebook");
        hashMap.put("LBL_ROLE","Vai trò");
        hashMap.put("LBL_COMMENTS","Ghi chú");
        hashMap.put("COMMENTS_NOTE_ONLY_1","Chỉ ghi chú");
        hashMap.put("COMMENTS_NOTE_ONLY_0","Ghi chú và phản hồi");
        hashMap.put("LBL_GENDER","Giới tính");
        hashMap.put("LBL_MALE","Nam");
        hashMap.put("LBL_FEMALE","Nữ");
        hashMap.put("LBL_OTHER_GENDER","Khác");
        hashMap.put("LBL_ADDRESS","Địa chỉ");
        hashMap.put("LBL_PRIMARY_EMAIL","Email chính");
        hashMap.put("LBL_DETAILS","Thông tin thêm");
        hashMap.put("LBL_NOTES","Chú ý");
        hashMap.put("LBL_TAGS","Tags");
        hashMap.put("LBL_LANGUAGE","Ngôn ngữ");
        hashMap.put("LBL_NEW_TICKET","Thêm mới phiếu ghi");
        hashMap.put("LBL_DELETE_CONTACT","Xóa");
        hashMap.put("LBL_MENU_ITEM_EMAIL_EDIT","Sửa");
        hashMap.put("LBL_MENU_ITEM_EMAIL_SEND","Gửi email");
        hashMap.put("LBL_MENU_ITEM_EMAIL_REMOVE","Xóa");
        hashMap.put("LBL_MENU_ITEM_PHONE_EDIT","Sửa");
        hashMap.put("LBL_MENU_ITEM_OPEN_PAGE","Mở trang cá nhân");
        hashMap.put("LBL_MENU_ITEM_PHONE_CALL","Gọi");
        hashMap.put("LBL_MENU_ITEM_PHONE_REMOVE","Xóa");
        hashMap.put("LBL_MENU_ITEM_PHONE_SEND_SMS","Gửi SMS");
        hashMap.put("LBL_MENU_ITEM_FACEBOOK_EDIT","Sửa");
        hashMap.put("LBL_MENU_ITEM_FACEBOOK_VIEW","Thông tin");
        hashMap.put("LBL_MENU_ITEM_FACEBOOK_REMOVE","Xóa");
        hashMap.put("LBL_CONTACT_DETAIL_ASSINGED_TICKET","Phiếu ghi được gán");
        hashMap.put("LBL_CONTACT_DETAIL_REQUESTED_TICKET","Phiếu ghi yêu cầu");
        hashMap.put("LBL_CONTACT_UPLOAD_PHOTO_DESCRIPTION","Upload a new Photo...");
        hashMap.put("LBL_CONTACT_NEW_CONTACT","Thêm khách hàng");
        hashMap.put("LBL_CONTACT_NEW_ORGANIZATION","Thêm cơ quan");
        hashMap.put("LBL_CONTACT_ORGANIZATION_NEW_NOTE","Enter domains separated with a space (e.g: acme.com). Users from these domains will be added to the organization.");
        hashMap.put("MESSAGE_NEW_CONTACT_SUCCESS","Đã tạo {{contact}} thành công");
        hashMap.put("MESSAGE_NEW_CONTACT_FAIL","Không thể tạo {{contact}} lúc này");
        hashMap.put("MESSAGE_UPDATE_CONTACT_SUCCESS","Đã cập nhật {{contact}} thành công");
        hashMap.put("MESSAGE_UPDATE_CONTACT_FAIL","Không thể cập nhật {{contact}} lúc này");
        hashMap.put("MESSAGE_UPDATE_CONTACT_INVALID","Cập nhật {{contact}} với giá trị không hơp lệ hoặc đã tồn tại");
        hashMap.put("MESSAGE_DELETE_CONTACT_SUCCESS","Đã xóa {{contact}} thành công");
        hashMap.put("MESSAGE_DELETE_CONTACT_FAIL","Không thể xóa {{contact}} lúc này");
        hashMap.put("_comments","Organization detail");
        hashMap.put("MESSAGE_NEW_ORGANIZATION_SUCCESS","Đã tạo {{organization}} thành công");
        hashMap.put("MESSAGE_NEW_ORGANIZATION_FAIL","Không thể tạo {{organization}} lúc này");
        hashMap.put("_comments","Report");
        hashMap.put("OVERVIEW_REPORT","Tổng quan");
        hashMap.put("OVERVIEW_REPORT_TICKETS_RECEIVED","Số lượng phiếu ghi nhận theo kênh");
        hashMap.put("OVERVIEW_REPORT_TICKETS_STATUS","Trạng thái xử lý phiếu ghi");
        hashMap.put("OVERVIEW_REPORT_AVG_RESOLVE_TIME","Thời gian xử lý trung bình");
        hashMap.put("OVERVIEW_REPORT_TICKET_SOLVED_NUM","Phiếu ghi đã giải quyết");
        hashMap.put("OVERVIEW_REPORT_SLA_RATE","Tỷ lệ xử lý phiếu ghi theo SLA");
        hashMap.put("OVERVIEW_REPORT_OUTBOUND","Outbound");
        hashMap.put("TICKET_REPORT","Báo cáo phiếu ghi");
        hashMap.put("TICKET_REPORT_SUMARY","Tổng hợp báo cáo ticket");
        hashMap.put("TICKET_REPORT_BY_CHANNEL","Ticket nhận theo từng kênh");
        hashMap.put("TICKET_REPORT_STATUS_PROCESSING","Trạng thái xử lý ticket");
        hashMap.put("TICKET_REPORT_STATUS_PROCESSING_SOLVED","Đã giải quyết");
        hashMap.put("TICKET_REPORT_STATUS_PROCESSING_PENDING","Tồn đọng");
        hashMap.put("TICKET_REPORT_AVGTIME","Thời gian trung bình");
        hashMap.put("TICKET_REPORT_AVGTIME","Thời gian trung bình");
        hashMap.put("TICKET_REPORT_ANSWER_COUNT","Số lượng trả lời ticket");
        hashMap.put("TICKET_REPORT_REOPEN","Số ticket đóng phải mở lại");
        hashMap.put("REPORT_SUM","Tổng");
        hashMap.put("REPORT_AVG","Trung bình");
        hashMap.put("TICKET_REPORT","Báo cáo phiếu ghi");
        hashMap.put("CHAT_REPORT","Báo cáo Chat");
        hashMap.put("CHAT_REPORT_SUMARY","Tổng hợp báo cáo chat");
        hashMap.put("CHAT_REPORT_TOTAL","Chat của khách hàng");
        hashMap.put("CHAT_REPORT_TOTAL_ANSWER","Trả lời chat");
        hashMap.put("CHAT_REPORT_TOTAL_MISS","Chat nhỡ");
        hashMap.put("CHAT_REPORT_ANSWERING_TIME","Thời gian trả lời 1 chat");
        hashMap.put("CHAT_REPORT_WATTING_TIME","Thời gian chờ 1 chat");
        hashMap.put("VOICE_REPORT","Báo cáo thoại");
        hashMap.put("VOICE_REPORT_SUMARY","Tổng hợp báo cáo thoại");
        hashMap.put("VOICE_REPORT_TOTAL_CALL","Thông tin số lượng cuộc gọi");
        hashMap.put("VOICE_REPORT_TIME_CALL","Thông tin thời gian cuộc gọi");
        hashMap.put("EMAIL_REPORT","Báo cáo kênh email");
        hashMap.put("OUTBOUND_REPORT","Báo cáo Outbound");
        hashMap.put("OUTBOUND_REPORT_SUMARY","Báo cáo Outbound");
        hashMap.put("OUTBOUND_REPORT_VOICE","Cuộc gọi ra");
        hashMap.put("OUTBOUND_REPORT_EMAIL","Email gửi ra");
        hashMap.put("OUTBOUND_REPORT_SMS","Sms gửi ra");
        hashMap.put("AGENT_REPORT","Báo cáo chi tiết");
        hashMap.put("AGENT_REPORT_LIST","Danh sách báo cáo");
        hashMap.put("AGENT_REPORT_SUB_REPORT_LIST","Chi tiết");
        hashMap.put("AGENT_REPORT_STATUS","Báo cáo thời gian trạng thái");
        hashMap.put("AGENT_REPORT_TICKET","Báo cáo phiếu ghi");
        hashMap.put("AGENT_REPORT_TICKET_NUM","Số lượng phiếu ghi theo kênh");
        hashMap.put("AGENT_REPORT_AVG_FIRST_REPLY","Thời gian trung bình trả lời lần đầu");
        hashMap.put("AGENT_REPORT_AVG_TICKET_SOLVED","Thời gian trung bình giải quyết phiếu ghi");
        hashMap.put("AGENT_REPORT_TICKET_CURRENT_STATUS","Tình trạng xử lý phiếu ghi");
        hashMap.put("AGENT_REPORT_TICKET_TYPE","Thống kê theo loại phiếu ghi");
        hashMap.put("AGENT_REPORT_TICKET_SLA_OK","Số lượng phiếu ghi đúng SLA");
        hashMap.put("AGENT_REPORT_TICKET_SLA_NOK","Số lượng phiếu ghi không đúng SLA");
        hashMap.put("AGENT_REPORT_TICKET_REOPEN","Số lượng phiếu ghi đã đóng và mở lại");
        hashMap.put("AGENT_REPORT_VOICE","Báo cáo thoại");
        hashMap.put("AGENT_REPORT_CHAT","Báo cáo chat");
        hashMap.put("AGENT_REPORT_OUTBOUND","Báo cáo Outbound");
        hashMap.put("AGENT_REPORT_OUTBOUND_VOICE","Báo cáo cuộc gọi ra");
        hashMap.put("AGENT_REPORT_OUTBOUND_VOICE_TOTAL","Số lượng gọi ra");
        hashMap.put("AGENT_REPORT_OUTBOUND_VOICE_MEET","Số lượng gọi ra gặp khách hàng");
        hashMap.put("AGENT_REPORT_OUTBOUND_VOICE_MISS","Số lượng gọi ra không gặp khách hàng");
        hashMap.put("AGENT_REPORT_OUTBOUND_EMAIL_SMS","Báo cáo Email và SMS gửi ra");
        hashMap.put("AGENT_REPORT_OUTBOUND_EMAIL","Số lượng Email gửi ra");
        hashMap.put("AGENT_REPORT_OUTBOUND_SMS","Số lượng Sms gửi ra");
        hashMap.put("AGENT_REPORT_SUMARY","Báo cáo chi tiết");
        hashMap.put("AGENT_REPORT_STATUS_LOGIN","Số lần đăng nhập");
        hashMap.put("AGENT_REPORT_STATUS_VOICE_A","Online kênh thoại");
        hashMap.put("AGENT_REPORT_STATUS_VOICE_NA","Offline kênh thoại");
        hashMap.put("AGENT_REPORT_STATUS_VOICE_NOANSWER","NoAnswer kênh thoại");
        hashMap.put("AGENT_REPORT_STATUS_CHAT_A","Online kênh Chat");
        hashMap.put("AGENT_REPORT_STATUS_CHAT_NA","Offline kênh Chat");
        hashMap.put("AGENT_REPORT_STATUS_EMAIL_A","Email AVAILABLE");
        hashMap.put("AGENT_REPORT_STATUS_EMAIL_NA","Email NOT AVAILABLE");
        hashMap.put("AGENT_REPORT_STATUS_SMS_A","SMS AVAILABLE");
        hashMap.put("AGENT_REPORT_STATUS_SMS_NA","SMS NOT AVAILABLE");
        hashMap.put("AGENT_REPORT_STATUS_TICKET_A","Online tiếp nhận phiếu ghi");
        hashMap.put("AGENT_REPORT_STATUS_TICKET_NA","Offline tiếp nhận phiếu ghi");
        hashMap.put("AGENT_REPORT_TICKET_RESOLVE","Đã giải quyết");
        hashMap.put("AGENT_REPORT_TICKET_NOT_RESOLVE","Tồn đọng");
        hashMap.put("AGENT_REPORT_PERCENTAGE","Tỉ lệ(%)");
        hashMap.put("AGENT_REPORT_SLA_OK","Đúng SLA");
        hashMap.put("AGENT_REPORT_SLA_NOK","Không đúng SLA");
        hashMap.put("AGENT_REPORT_FIRST_REPLY","Lần đầu trả lời");
        hashMap.put("AGENT_REPORT_MULTI_REPLY","Nhiều lần trả lời");
        hashMap.put("LBL_QUANTITY","Số lượng");
        hashMap.put("FILTER_BY_AGENT","Chọn Agent");
        hashMap.put("REPORT_BY","Báo cáo theo:");
        hashMap.put("REPORT_BY_SUBREPORT","Báo cáo:");
        hashMap.put("PERIOD_TIME","Thời gian");
        hashMap.put("PERIOD_TIME_30","30 ngày gần nhất");
        hashMap.put("PERIOD_TIME_7","7 ngày gần nhất");
        hashMap.put("PERIOD_TIME_1","24 giờ gần nhất");
        hashMap.put("PERIOD_TIME_CUSTOM","Tùy chọn");
        hashMap.put("PERIOD_TIME_START","Từ:");
        hashMap.put("PERIOD_TIME_END","Đến:");
        hashMap.put("LBL_ALL","Tất cả");
        hashMap.put("_comments","Common");
        hashMap.put("BTN_SAVE","Lưu");
        hashMap.put("BTN_UPDATE","Cập nhật");
        hashMap.put("BTN_CANCEL","Hủy");
        hashMap.put("BTN_CLOSE","Đóng");
        hashMap.put("BTN_SEND","Gửi");
        hashMap.put("LBL_EDIT","Chỉnh sửa");
        hashMap.put("LBL_DELETE","Xóa");
        hashMap.put("LBL_MARK_SPAM","Đánh dấu spam");
        hashMap.put("LBL_CLEAR_SELECTION","Hủy các bản ghi đã chọn");
        hashMap.put("LBL_EXPORT_CSV","Xuất ra file CSV");
        hashMap.put("BTN_ADD_CONTACT","Thêm liên lạc");
        hashMap.put("LBL_SELECT_ACTION","Chọn 1 hành động");
        hashMap.put("CONFIRM_REFRESH_PAGE","Tải lại trang có thể làm ảnh hưởng đến dữ liệu của bạn. Bạn có chắc chắn muốn tải lại trang không?");
        hashMap.put("NOTIFY_BROWSER_INVALID","Hệ thống không hỗ trợ trình duyệt bạn đang sử dụng. Hãy cập nhật trình duyệt phiên bản mới hơn!");
        hashMap.put("SEMD_HELP_CONTENT","Yêu cầu trợ giúp từ domain: {{domain}}<br/><b>Nội dung:</b><br/>");
        hashMap.put("VALIDATE_CHANGEPASS_TITLE","<h1>Lỗi thay đổi mật khẩu:</h1>");
        hashMap.put("VALIDATE_CHANGEPASS_OLDVALUE_NULL","<li>Mật khẩu cũ không được để trống</li>");
        hashMap.put("VALIDATE_CHANGEPASS_NEWVALUE_NULL","<li>Mật khẩu mới không được để trống</li>");
        hashMap.put("VALIDATE_CHANGEPASS_MORE_6_CHAR","<li>Mật khẩu phải có ít nhất 6 ký tự</li>");
        hashMap.put("VALIDATE_CHANGEPASS_SAME_OLDVALUE","<li>Mật khẩu mới không được giống với mật khẩu cũ</li>");
        hashMap.put("VALIDATE_CHANGEPASS_NOT_MATCH","<li>Xác nhận mật khẩu không chính xác</li>");
        hashMap.put("MESSAGE_CHANGEPASS_FAILURE","Đổi mật khẩu không thành công");
        hashMap.put("MESSAGE_CHANGEPASS_SUCCESS","Đổi mật khẩu thành công");
        hashMap.put("MESSAGE_CHANGEPASS_INVALID","Mật khẩu cũ không đúng");
        hashMap.put("MESSAGE_VOICE_NOANSWER_MORE","Bạn đã từ chối cuộc gọi quá số lần quy định");
        hashMap.put("MESSAGE_VOICE_TRANSFER_SUCCESS","Cuộc gọi của bạn đã được chuyển đi");
        hashMap.put("MESSAGE_VOICE_TRANSFER_FAILURE","Chuyển cuộc gọi không thành công!");
        hashMap.put("NOTIFY_VOICE_NEW_CALL","Bạn có 1 cuộc gọi mới");
        hashMap.put("NOTIFY_VOICE_NEW_CALL_SDT","Số điện thoại:");
        hashMap.put("_comments","SearchAll");
        hashMap.put("LBL_SEARCH_BY","Tìm kiếm  ");
        hashMap.put("LBL_ADVANCED_SEARCH","Tìm kiếm nâng cao");
        hashMap.put("LBL_TICKET_CREATED","Phiếu ghi #{{ticketNo}} đã được tạo");
        hashMap.put("LBL_TICKET_UPDATED","Phiếu ghi #{{ticketNo}} đã được cập nhật");
        hashMap.put("INVALID_NUMBER","Số điện thoại không hợp lệ!");
        hashMap.put("_comments","Entity");
        hashMap.put("ENTITY_VOICE","ENTITY_VOICE");
        hashMap.put("ENTITY_CHAT","ENTITY_CHAT");
        hashMap.put("TOTAL_SIMPLE","Tổng");
        hashMap.put("PENDING_SIMPLE","Tồn đọng");
        hashMap.put("SOLVED_SIMPLE","Đã giải quyết");
        hashMap.put("TICKET_CHANNEL","Kênh");
        hashMap.put("TICKET_TOTAL","Tổng");
        hashMap.put("TICKET_PENDING","Phiếu ghi tồn đọng");
        hashMap.put("TICKET_SOLVED","Phiếu ghi đã giải quyết");
        hashMap.put("TICKET_UNSOLVED","Phiếu chưa giải quyết");
        hashMap.put("AVG_RESPONSE","Thời gian trung bình có phản hồi(phút)");
        hashMap.put("AVG_CUSTOMER_REPLY","Trung bình số lượng khách hàng trả lời ticket");
        hashMap.put("AVG_ANSWER_TICKET","Trung bình số lượng trả lời ticket của agent");
        hashMap.put("AVG_FIRST_REPLY","Thời gian trung bình lượt trả lời đầu tiên");
        hashMap.put("AVG_FIRST_REPLY_MIN","Thời gian trung bình lượt trả lời đầu tiên(phút)");
        hashMap.put("AVG_TICKET_SOLVED","Thời gian trung bình phiếu ghi được đóng");
        hashMap.put("AVG_TICKET_SOLVED_MIN","Thời gian trung bình phiếu ghi được đóng(phút)");
        hashMap.put("TOTAL_CHAT","Tổng chat của khách hàng");
        hashMap.put("TOTAL_ANSWER_CHAT","Tổng trả lời chat");
        hashMap.put("TOTAL_MISS_CHAT","Tổng chat nhỡ");
        hashMap.put("AVG_ANSWER_CHAT","Thời gian trung bình trả lời một chat");
        hashMap.put("AVG_WAIT_CHAT","Thời gian chờ trung bình một chat");
        hashMap.put("REOPEN_TICKET","Số ticket đã đóng nhưng phải mở lại");
        hashMap.put("NO_DATA_SHOW","Không có dữ liệu được hiển thị");
        hashMap.put("TOTAL_CALL","Tổng cuộc gọi của khách hàng");
        hashMap.put("TOTAL_MEET","Tổng cuộc gọi được trả lời");
        hashMap.put("TOTAL_MISS","Tổng cuộc gọi nhỡ");
        hashMap.put("TOTAL_MISS_BY_CUSTOMER","Tổng cuộc gọi rớt do khách hàng");
        hashMap.put("TOTAL_MISS_BY_AGENT","Tổng cuộc gọi rớt do chuyên viên");
        hashMap.put("TOTAL_MISS_BY_SYSTEM","Tổng cuộc gọi rớt do hệ thống");
        hashMap.put("AVG_HOLD","Thời gian giữ máy trung bình");
        hashMap.put("AVG_TALK","Thời gian đàm thoại trung bình");
        hashMap.put("AVG_WAIT","Thời gian chờ trung bình");
        hashMap.put("LBL_SOLVED_WEB","Đã giải quyết Web");
        hashMap.put("LBL_PENDING_WEB","Tồn đọng Web");
        hashMap.put("LBL_SOLVED_VOICE","Đã giải quyết Voice");
        hashMap.put("LBL_PENDING_VOICE","Tồn đọng Voice");
        hashMap.put("LBL_SOLVED_CHAT","Đã giải quyết Chat");
        hashMap.put("LBL_PENDING_CHAT","Tồn đọng Chat");
        hashMap.put("LBL_SOLVED_EMAIL","Đã giải quyết Email");
        hashMap.put("LBL_PENDING_EMAIL","Tồn đọng Email");
        hashMap.put("LBL_SOLVED_VOICEMAIL","Đã giải quyết Voicemail");
        hashMap.put("LBL_PENDING_VOICEMAIL","Tồn đọng Voicemail");
        hashMap.put("LBL_SOLVED_FACEBOOK","Đã giải quyết Facebook");
        hashMap.put("LBL_PENDING_FACEBOOK","Tồn đọng Facebook");
        hashMap.put("LBL_TOTAL_CALLOUT","Tổng cuộc gọi ra");
        hashMap.put("LBL_TOTAL_CALLOUT_OK","Tổng cuộc gọi ra gặp khách hàng");
        hashMap.put("LBL_TOTAL_CALLOUT_MISS","Tổng cuộc gọi không gặp khách hàng");
        hashMap.put("LBL_TOTAL_SENDOUT_EMAIL","Tổng email gửi ra");
        hashMap.put("LBL_TOTAL_SENDOUT_SMS","Tổng Sms gửi ra");
        hashMap.put("UNSAVED_SMS_MESSAGE","Bạn có 1 SMS đang soạn dở. Bạn có muốn reset lại dữ liệu ko?");
        hashMap.put("UNSAVED_EMAIL_MESSAGE","Bạn có 1 email đang soạn dở. Bạn có muốn reset lại dữ liệu ko?");
        hashMap.put("_comment","AnhNT206");
        hashMap.put("LBL_ADD","Thêm");
        hashMap.put("LBL_ADD_NEW","Thêm mới...");
        hashMap.put("LBL_SEARCH","Tìm kiếm");
        hashMap.put("LBL_RECENTLY_UPDATED_TICKETS","Các phiếu ghi cập nhật gần nhất...");
        hashMap.put("LBL_VIEW_PROFILE","Xem trang cá nhân");
        hashMap.put("LBL_SIGN_OUT","Đăng xuất");
        hashMap.put("TICKET_TYPE_QUESTION","Câu hỏi");
        hashMap.put("TICKET_TYPE_PROBLEM","Vấn đề");
        hashMap.put("TICKET_TYPE_TASK","Nhiệm vụ");
        hashMap.put("-","-");
        hashMap.put("LBL_MONITORING","Giám sát");
        hashMap.put("LBL_MONITORING_VOICE","Thoại");
        hashMap.put("LBL_MONITORING_CHAT","Chat");
        hashMap.put("LBL_MONITORING_AGENT","Agent");
        hashMap.put("LBL_AGENT_STATUS_AVAILABLE","Available");
        hashMap.put("LBL_AGENT_STATUS_NOT_AVAILABLE","Not Available");
        hashMap.put("LBL_QUEUE","Queue");
        hashMap.put("LBL_MONITORING_CURRENT_ACTIVITY","Hoạt động hiện tại");
        hashMap.put("LBL_MONITORING_ACTIVITY","Hoạt động trong ngày");
        hashMap.put("LBL_MONITORING_WATING_CALL","Cuộc gọi đang chờ");
        hashMap.put("LBL_MONITORING_ANSWERING_CALL","Cuộc gọi đang trả lời");
        hashMap.put("LBL_MONITORING_TOTAL_CALL","Tổng số cuộc gọi");
        hashMap.put("LBL_MONITORING_TOTAL_AGENT","Số lượng Agent đăng nhập");
        hashMap.put("LBL_MONITORING_TOTAL_ONLINE_AGENT","Số lượng Agent Online");
        hashMap.put("LBL_MONITORING_AVERAGE_WAIT_TIME","Thời gian chờ trung bình");
        hashMap.put("LBL_MONITORING_RESPONSE_RATIO","Tỷ lệ tiếp nhận cuộc gọi");
        hashMap.put("LBL_MONITORING_TOTAL_AVERAGE_CALLS","Số cuộc gọi trung bình 1 Agent");
        hashMap.put("LBL_MONITORING_ANSWER_TIME_PER_AGENT","Thời gian trả lời trung bình 1 Agent");
        hashMap.put("LBL_MONITORING_ANSWER_TIME_PER_CALL","Thời gian trả lời trung bình 1 cuộc gọi");
        hashMap.put("LBL_MONITORING_HOLD_TIME","Số lần hold máy");
        hashMap.put("LBL_MONITORING_HOLD_AVERAGE_TIME","Thời gian hold máy trung bình");
        hashMap.put("LBL_MONITORING_MISS_CALL","Số cuộc gọi nhỡ");
        hashMap.put("LBL_MONITORING_REJECT_CALL","Số lần từ chối cuộc gọi");
        hashMap.put("LBL_MONITORING_WATING_CHAT","Số Chat đang chờ");
        hashMap.put("LBL_MONITORING_ANSWERING_CHAT","Số Chat đang trả lời");
        hashMap.put("LBL_MONITORING_TOTAL_AGENT_CHAT","Số lượng Agent đăng nhập");
        hashMap.put("LBL_MONITORING_TOTAL_ONLINE_AGENT_CHAT","Số lượng Agent Available");
        hashMap.put("LBL_MONITORING_TOTAL_CHAT","Tổng số cuộc chat");
        hashMap.put("LBL_MONITORING_TOTAL_ANSWERED_CHAT","Số chat tiếp nhận");
        hashMap.put("LBL_MONITORING_MISS_CHAT","Số chat nhỡ");
        hashMap.put("LBL_MONITORING_MISS_CHAT_NO_AGENT","Số chat nhỡ do không có Agent");
        hashMap.put("LBL_MONITORING_CHAT_WAIT_TIME","Thời gian chờ trung bình");
        hashMap.put("LBL_MONITORING_CHAT_ANSWER_TIME","Thời gian trả lời trung bình");
        hashMap.put("LBL_AGENT_ACTIVITY","Hoạt động thoại trong ngày của Agent");
        hashMap.put("LBL_AGENT_CHAT_ACTIVITY","Hoạt động chat trong ngày của Agent");
        hashMap.put("LBL_USERNAME","Tên Agent");
        hashMap.put("LBL_AGENT_STATUS","Trạng thái");
        hashMap.put("LBL_TIME_AVAILABLE","Thời gian online");
        hashMap.put("LBL_CALLS_ACCEPT","Số cuộc gọi tiếp nhận");
        hashMap.put("LBL_CALLS_DENY","Số cuộc gọi từ chối");
        hashMap.put("LBL_AVERAGE_ANSWER_TIME","Thời gian tiếp nhận trung bình");
        hashMap.put("LBL_TOTAL_ANSWER_TIME","Tổng thời gian tiếp nhận");
        hashMap.put("LBL_NUMBER_ANSWER_CHAT","Số chat tiếp nhận");
        hashMap.put("LBL_NUMBER_MISS_CHAT","Số chat nhỡ");
        hashMap.put("_comments","Report");
        hashMap.put("LBL_REPORT","Báo cáo");
        hashMap.put("SUBJECT_NOT_EMPTY","Bạn chưa nhập chủ đề");
        hashMap.put("COMMENT_NOT_EMPTY","Bạn chưa nhập mô tả");
        hashMap.put("ENABLE_VOICE_CONFIRM","Kích hoạt tính năng voice có thể gây ảnh hưởng đến cuộc gọi. Bạn có chắc chắn muốn thực hiện không?");
        hashMap.put("LBL_INCOMING_CALL","Cuộc gọi đến");
        hashMap.put("LBL_OUTGOING_CALL","Cuộc gọi ra");
        hashMap.put("BTN_CALL","Gọi");
        hashMap.put("BTN_CALLING","Đang kết nối tới Agent...");
        hashMap.put("LBL_CURRENTLY_OFFLINE","Bạn đang offline");
        hashMap.put("LBL_NO_INCOMING_CALLS","Không có cuộc gọi đến");
        hashMap.put("LBL_MISSED_CALL","Cuộc gọi nhỡ");
        hashMap.put("LBL_TICKET_FOR_CALL","Phiếu ghi cho cuộc gọi:");
        hashMap.put("BTN_DECLINE_CALL","Từ chối");
        hashMap.put("BTN_ACCEPT_CALL","Tiếp nhận");
        hashMap.put("BTN_HANG_UP","Kết thúc");
        hashMap.put("BTN_TRANSFER","Chuyển");
        hashMap.put("BTN_ENABLE_VOICE","Kích hoạt thoại");
        hashMap.put("LBL_ENABLE_VOICE_TO_CALL","Hãy kích hoạt thoại để có thể gọi tới khách hàng");
        hashMap.put("LBL_TRANSFER_REQUEST","Yêu cầu chuyển cuộc gọi");
        hashMap.put("LBL_TRANSFER_MESSAGE","Bạn nhận được yêu cầu chuyển cuộc gọi từ");
        hashMap.put("LBL_TRANSFER_AGENT","Chuyển cuộc gọi sang Agent khác");
        hashMap.put("LBL_TRANSFER_PROF","Chuyển cuộc gọi ra số điện thoại ngoài");
        hashMap.put("AGENT_LIST","Danh sách Agent");
        hashMap.put("PROF_LIST","Danh sách số điện thoại");
        hashMap.put("LBL_CONFIRMATION","Xác nhận");
        hashMap.put("LBL_CONFIRMATION_CHANGE_DEVICE","Để thay đổi thiết bị tiếp nhận thì hệ thống sẽ thực hiện tải lại trang. Bạn có muốn tiếp tục thực hiện không?");
        hashMap.put("LBL_NOTIFICATION","Thông báo");
        hashMap.put("LBL_VERSION","Phiên bản 1.1");
        hashMap.put("LBL_CHANGE_PWD","Đổi mật khẩu");
        hashMap.put("LBL_CURRENT_PWD","Mật khẩu hiện tại");
        hashMap.put("LBL_NEW_PWD","Mật khẩu mới");
        hashMap.put("LBL_CONFIRM_PWD","Xác nhận mật khẩu mới");
        hashMap.put("BTN_CHANGE_PWD","Thay đổi");
        hashMap.put("LBL_VIA_BROWSER","Nhận cuộc gọi qua trình duyệt");
        hashMap.put("LBL_VIA_SOFTPHONE","Nhận cuộc gọi qua IP Phone");
        hashMap.put("LBL_VIA_MOBILE","Chuyển cuộc gọi ra số điện thoại: ");
        hashMap.put("LBL_VIA_NO_WEB","Chế độ không ngồi máy (nhận cuộc gọi qua IP Phone/Mobile App)");
        hashMap.put("BTN_ENTER_NUMBER_CALLOUT","Nhập số điện thoại gọi ra...");
        hashMap.put("ERROR_CALLOUT","Không thể gọi ra khi đang tiếp nhận cuộc gọi");
        hashMap.put("ERROR_CALLOUT_CONNECT","Kết nối không thành công. Vui lòng thử lại sau.");
        hashMap.put("IPCC_NOT_CONNECT_AGENT_ID","Không thể kết nối được đến ĐTV");
        hashMap.put("IPCC_CUSTOMER_REJECT","Khách hàng từ chối tiếp nhận cuộc gọi");
        hashMap.put("IPCC_CUSTOMER_TIMEOUT","Khách hàng không nghe máy");
        hashMap.put("IPCC_CUSTOMER_NOT_CONNECT","Thuê bao khách hàng tạm thời không liên lạc được");
        hashMap.put("ERROR_CHANGE_DEVICE_TYPE","Đổi thiết bị tiếp nhận không thành công. Vui lòng thử lại sau");
        hashMap.put("MAX_SIZE_UPLOAD","File đính kèm không được lớn hơn 15mb");
        hashMap.put("UPLOAD_ERROR","Upload file không thành công");
        hashMap.put("IPCCERR0000","Không tìm thấy cuộc gọi");
        hashMap.put("IPCCERR0001","Agent đang bận");
        hashMap.put("IPCCERR0002","Không tìm thấy Agent");
        hashMap.put("IPCCERR0003","Agent đang hold hoặc đang mute");
        hashMap.put("IPCCERR0006","Không tìm thấy khách hàng");
        hashMap.put("IPCCERR0008","Không thể hold khi cuộc gọi đang ring");
        hashMap.put("IPCCERR0009","Không thể mute khi cuộc gọi đang ring");
        hashMap.put("SUBMIT_TICKET_ERROR","Không thể lưu được phiếu ghi. Xin hãy thử lại sau");
        hashMap.put("OPEN_TICKET_ERROR","Không thể lấy được thông tin phiếu ghi");
        hashMap.put("OPEN_CONTACT_ERROR","Không thể lấy được thông tin người dùng");
        hashMap.put("LBL_CHANGE_REQUESTER","Thay đổi");
        hashMap.put("LBL_ATTACK_FILE","Đính kèm file");
        hashMap.put("LBL_CLOSE_TAB","Đóng tab");
        hashMap.put("LBL_STAY_ON_TICKET","Giữ phiếu ghi");
        hashMap.put("LBL_NO_TICKET","Không tìm thấy thông tin phiếu ghi");
        hashMap.put("LBL_NO_CONTACT","Không tìm thấy thông tin người dùng");
        hashMap.put("LBL_VISITOR_PATH","Truy cập của người dùng");
        hashMap.put("LBL_ADD_NAME","Nhập tên");
        hashMap.put("LBL_ADD_EMAIL","Nhập email");
        hashMap.put("LBL_UNDEFINED","Không xác định");
        hashMap.put("LBL_NAME_UNDEFINED","Tên không xác định");
        hashMap.put("LBL_EMAIL_UNDEFINED","Email không xác định");
        hashMap.put("LBL_PHONE_UNDEFINED","Số điện thoại không xác định");
        hashMap.put("LBL_ADD_PHONE","Nhập số điện thoại");
        hashMap.put("LBL_LOCATION","Địa điểm");
        hashMap.put("LBL_BROWSER","Trình duyệt");
        hashMap.put("LBL_PLATFORM","Hệ điều hành");
        hashMap.put("LBL_DEVICE","Thiết bị");
        hashMap.put("LBL_IP_ADDRESS","Địa chỉ IP");
        hashMap.put("LBL_USER_AGENT","User Agent");
        hashMap.put("LBL_SEND_EMAIL","Gửi email phản hồi cho phiếu ghi:");
        hashMap.put("LBL_SEND_SMS","Gửi SMS phản hồi cho phiếu ghi:");
        hashMap.put("LBL_SEND","Gửi");
        hashMap.put("LBL_SUBJECT","Tiêu đề");
        hashMap.put("LBL_MESSAGE","Tin nhắn");
        hashMap.put("LBL_SOLVED","Giải quyết");
        hashMap.put("_comments","RESPONDE_MESSAGE");
        hashMap.put("PERMISSION_DENIED_MESSAGE","Bạn không có quyền thực hiện thao tác này!");
        hashMap.put("SEND_SMS_OK_MESSAGE","Đã tiếp nhận yêu cầu của bạn!");
        hashMap.put("LBL_CONFIRM_LOGOUT","Bạn đang trong trạng thái tiếp nhận cuộc gọi không cần đăng nhập trình duyệt. Sau khi đăng xuất bạn có muốn tiếp tục nhận cuộc gọi hay không?");
        hashMap.put("BTN_LOGOUT_WEB","Đăng xuất, có nhận cuộc gọi");
        hashMap.put("BTN_LOGOUT_ALL","Đăng xuất, không nhận cuộc gọi");
        hashMap.put("TITLE_REPLY_OUT","Tương tác ra ngoài cho khách hàng");
        hashMap.put("TITLE_CALLOUT","Gọi ra ngoài cho khách hàng");
        hashMap.put("TITLE_SEND_EMAIL","Gửi email ra ngoài cho khách hàng");
        hashMap.put("TITLE_SEND_SMS","Gửi SMS ra ngoài cho khách hàng");
        hashMap.put("LBL_REASSIGN","Giao cho chuyên viên");
        hashMap.put("LBL_REASSIGN_AGENT","Giao nhiệm vụ cho nhân viên");
        hashMap.put("REASSIGN_NOT_SELECT_AGENT","Bạn chưa chọn chuyên viên để giao phiếu ghi");
        hashMap.put("MESSAGE_REASSIGN_TICKET_SUCCESS","Chuyển phiếu ghi thành công");
        hashMap.put("MESSAGE_REASSIGN_TICKET_FAIL","Chuyển phiếu ghi thất bại");
        hashMap.put("LBL_HIDE_COMMENT","Ẩn bình luận");
        hashMap.put("LBL_UNHIDE_COMMENT","Hiện bình luận");
        hashMap.put("LBL_REMOVE_COMMENT","Xóa bình luận");
        hashMap.put("LBL_HIDED","Bình luận đã bị ẩn");
        hashMap.put("LBL_DELETED","Bình luận đã bị xóa");
        hashMap.put("LBL_VIEW_EMAIL","Xem chi tiết Email");
        hashMap.put("LBL_SYSTEM_ERROR","Có lỗi xảy ra. Vui lòng thử lại sau");
        hashMap.put("LBL_UNHIDE_SUCCESS","Bỏ ẩn bình luận thành công");
        hashMap.put("LBL_HIDE_SUCCESS","Ẩn bình luận thành công");
        hashMap.put("LBL_DELETE_SUCCESS","Xóa bình luận thành công");
        hashMap.put("LBL_CAN_NOT_CHANGE_CALL_STATUS","Bạn không thể đổi trạng thái thoại về Offline khi đang ở chế độ không ngồi máy");
        hashMap.put("LBL_HELP","Liên hệ với hỗ trợ Caresoft");
        hashMap.put("LBL_ISSUE_TYPE","Phân loại");
        hashMap.put("LBL_CONTENT","Nội dung");
        hashMap.put("LBL_ATTACK_FILE_HELP","Đính kèm");
        hashMap.put("FACEBOOK_ATTACK_FILE_ERROR","Facebook chỉ cho phép đính kèm 1 file");
        hashMap.put("SEND_HELP_OK","Gửi tin nhắn thành công. Chúng tôi sẽ liên hệ lại với bạn trong thời gian sớm nhất.");
        hashMap.put("_comments","CHAT");
        hashMap.put("LBL_CHAT_TITLE","CS Chat");
        hashMap.put("LBL_CHAT_RECONNECT_TO_CHAT","Kết nối lại để chat");
        hashMap.put("LBL_CHAT_RECONNECTING","Đang kết nối lại...");
        hashMap.put("LBL_CHAT_LIST_CONVERSATION","Danh sách hội thoại");
        hashMap.put("LBL_CHAT_STATUS_ONLINE","Online");
        hashMap.put("LBL_CHAT_STATUS_OFFLINE","Offline");
        hashMap.put("LBL_CHAT_AGENT_ONLINE","TVV trực tuyến");
        hashMap.put("LBL_CHAT_AGENT_STATUS_ONLINE","online");
        hashMap.put("LBL_CHAT_NO_REQUEST","Không có yêu cầu nào");
        hashMap.put("LBL_CHAT_ACCEPT_REQUEST","Tiếp nhận {{chatRequest}} yêu cầu");
        hashMap.put("LBL_CHAT_CURRENT_CHAT","Đang chat");
        hashMap.put("LBL_CHAT_HISTORY","Lịch sử chat");
        hashMap.put("LBL_CHAT_HISTORY_TIME","Hội thoại diễn ra lúc {{time}}");
        hashMap.put("LBL_CHAT_HISTORY_RATING","Đánh giá");
        hashMap.put("LBL_CHAT_HISTORY_RATING_0","-");
        hashMap.put("LBL_CHAT_HISTORY_RATING_1","Tốt");
        hashMap.put("LBL_CHAT_HISTORY_RATING_2","Kém");
        hashMap.put("LBL_CHAT_HISTORY_CUSTCOMMENT","Nhận xét");
        hashMap.put("LBL_CHAT_VISITOR_INFO","Thông tin khách hàng");
        hashMap.put("BTN_CHAT_NEXT","Chuyển Chat");
        hashMap.put("LBL_CHAT_SENDING","Đang gửi...");
        hashMap.put("LBL_CHAT_RESEND","Gửi lại");
        hashMap.put("LBL_CHAT_SENDING_FAILED","Gửi lỗi");
        hashMap.put("LBL_CHAT_YOU_SENT","Bạn đã gửi:");
        hashMap.put("LBL_CHAT_PARTNER_SENT","đã gửi:");
        hashMap.put("LBL_VIEW_PREVIOUS_CHAT","Xem hội thoại trước");
        hashMap.put("LBL_CHAT_REQUEST_RATING","Yêu cầu đánh giá từ khách hàng");
        hashMap.put("LBL_CHAT_NO_MATCHE_SHORTCUT_1","No matching shortcuts.");
        hashMap.put("LBL_CHAT_NO_MATCHE_SHORTCUT_2","Remove the slash to search the full shortcut messages.");
        hashMap.put("LBL_CHAT_UPLOADING","Đang tải lên...");
        hashMap.put("LBL_CHAT_ATTACK","Đính kèm");
        hashMap.put("LBL_CHAT_CUST_OFFLINE","đã ngoại tuyến.");
        hashMap.put("LBL_CHAT_NO_CHAT_PRE","Không có chat trong quá khứ");
        hashMap.put("LBL_CHAT_AGENT","Agent");
        hashMap.put("LBL_CHAT_TIME","Thời gian");
        hashMap.put("LBL_CHAT_RECEIVE_TIME","Tiếp nhận vào");
        hashMap.put("LBL_CHAT_FACEBOOKID","Trang cá nhân");
        hashMap.put("LBL_CHAT_FACEBOOK_PAGE","Page:");
        hashMap.put("LBL_CHAT_TRANSFER_TO_AGENT","Chuyển hội thoại sang TVV khác");
        hashMap.put("LBL_CHAT_TRANSFER_AGENT_NAME","Tên TVV");
        hashMap.put("PHR_CHAT_TRANSFER_AGENT_NAME_INPUT","Nhập tên TVV và chọn từ danh sách");
        hashMap.put("LBL_CHAT_TRANSFER_NO_AGENT","Chưa chọn TVV để thực hiện chuyển");
        hashMap.put("BTN_CHAT_TRANSFER","Chuyển");
        hashMap.put("BTN_CHAT_TRANSFER_CANCEL","Bỏ qua");
        hashMap.put("PHR_CHAT_NO_CHAT","Bạn đang không tiếp nhận hội thoại nào.");
        hashMap.put("PHR_CHAT_LIST_CHAT","Những hội thoại được bạn tiếp nhận sẽ xuất hiện ở đây");
        hashMap.put("LBL_CHAT_TICKET_SUBJECT","Chat với người dùng: ");
        hashMap.put("LBL_CHAT_TICKET_COMMENT_USERNAME","Tên người dùng: ");
        hashMap.put("LBL_CHAT_TICKET_COMMENT_EMAIL","Email: ");
        hashMap.put("LBL_CHAT_TICKET_COMMENT_PHONE","Số điện thoại: ");
        hashMap.put("LBL_CHAT_TICKET_COMMENT_STARTTIME","<p>Hội thoại bắt đầu lúc ");
        hashMap.put("LBL_CHAT_CONTENT_LEFT"," đã thoát hội thoại");
        hashMap.put("LBL_CHAT_CONTENT_JOIN"," đã tham gia hội thoại");
        hashMap.put("MESSAGE_CHAT_TRANSFER_AGENT_BUSY"," đang bận");
        hashMap.put("MESSAGE_CHAT_TRANSFER_AGENT_NOTFOUND","Không tìm thấy TVV");
        hashMap.put("MESSAGE_CHAT_TRANSFER_UNABLE","Không thể chuyển được cho TVV ");
        hashMap.put("MESSAGE_CHAT_TRANSFER_CANT","Không thể thực hiện chuyển được hội thoại này");
        hashMap.put("MESSAGE_CHAT_TRANSFER_AGENT_ACCEPTED"," đã chấp nhận yêu cầu transfer chat");
        hashMap.put("MESSAGE_CHAT_TRANSFER_AGENT_DENIED"," đã từ chối yêu cầu transfer chat");
        hashMap.put("MESSAGE_CHAT_TRANSFER_CONV_ENDED","Không tìm thấy hội thoại!");
        hashMap.put("MESSAGE_CHAT_TRANSFER_CONV_NOT_FOUND","Không tìm thấy TVV được yêu cầu!");
        hashMap.put("LBL_CHAT_NEW_REQUEST","Bạn có yêu cầu chat mới");
        hashMap.put("LBL_CHAT_SERVICE","Dịch vụ: ");
        hashMap.put("LBL_CHAT_NEW_TRANSFER_REQUEST","Bạn có yêu cầu chuyển chat mới");
        hashMap.put("LBL_CHAT_TRANSFER_AGENT","Người chuyển: ");
        hashMap.put("LBL_CHAT_NEW_MESSAGE","Tin nhắn mới từ ");
        hashMap.put("_comments","EMAIL");
        hashMap.put("LBL_EMAIL_TITLE","CS Email");
        hashMap.put("_comments","TICKET");
        hashMap.put("LBL_TICKET_STATUS_ONLINE","CS Ticket - Online");
        hashMap.put("LBL_TICKET_STATUS_OFFLINE","CS Ticket - Offline");
        hashMap.put("_comments","VOICE");
        hashMap.put("LBL_VOICE_TITLE","CS Voice");
        hashMap.put("LBL_VOICE_CALLOUT_BY_TICKET","Gọi ra ngoài cho phiếu ghi:");
        hashMap.put("LBL_VOICE_MORE_USING_THIS_PHONE","(*) Có nhiều người dùng sử dụng số điện thoại này");
        hashMap.put("_comments","SMS");
        hashMap.put("LBL_SMS_TITLE","CS Sms");
        hashMap.put("_comments","INDEX");
        hashMap.put("LBL_INDEX_LOST_CONNECTION","Đang có vấn đề về kết nối.");
        hashMap.put("LBL_INDEX_RECONNECT","Hệ thống đang thử kết nối lại...");
        hashMap.put("LBL_INDEX_CLICK_HERE","Nhấn vào đây");
        hashMap.put("LBL_INDEX_TO_RECONNECT","để thử kết nối lại");
        hashMap.put("LBL_INDEX_ADMIN_CONFIG","CẤU HÌNH");
        hashMap.put("LBL_INDEX_ADMIN_CONFIG_AGENT","Chuyên viên");
        hashMap.put("LBL_INDEX_ADMIN_CONFIG_GROUP","Bộ phận");
        hashMap.put("LBL_INDEX_ADMIN_CONFIG_CUST","Người dùng");
        hashMap.put("LBL_INDEX_ADMIN_CONFIG_CRM","Liên kết đến CRM");
        hashMap.put("LBL_INDEX_ADMIN_SERVICE","DỊCH VỤ");
        hashMap.put("LBL_INDEX_ADMIN_SERVICE_VOICE","Thoại");
        hashMap.put("LBL_INDEX_ADMIN_SERVICE_CHAT","Chat");
        hashMap.put("LBL_INDEX_ADMIN_SERVICE_EMAIL","Email");
        hashMap.put("LBL_INDEX_ADMIN_SERVICE_FACEBOOK","Facebook");
        hashMap.put("LBL_INDEX_ADMIN_SERVICE_SMS","SMS");
        hashMap.put("BTN_INDEX_HELP","Trợ giúp");
        hashMap.put("_comments","LOGIN");
        hashMap.put("LBL_LOGIN_TITLE","Đăng nhập với");
        hashMap.put("PHR_LOGIN_YOUR_EMAIL","Nhập Email của bạn");
        hashMap.put("PHR_LOGIN_YOUR_PASSWORD","Mật khẩu");
        hashMap.put("BTN_LOGIN","Đăng nhập");
        hashMap.put("MESSAGE_LOGIN_INVALID","Tên đăng nhập / mật khẩu không chính xác.");
        hashMap.put("MESSAGE_LOGIN_FAILURE","Đăng nhập không thành công. Vui lòng thử lại sau.");
        hashMap.put("MESSAGE_LOGIN_EXPIRE","Tài khoản của bạn đã hết hạn sử dụng. Để tiếp tục sử dụng dịch vụ, xin hãy liên hệ với đội ngũ Chăm sóc khách hàng của Caresoft.");
        hashMap.put("WARNING_EXPIRE_DATE","Tài khoản của bạn sẽ hết hạn trong {{day}} ngày tới. Hãy liên hệ với bộ phận chăm sóc khách hàng Caresoft để gia hạn tài khoản của bạn");
        hashMap.put("WARNING_EXPIRE_DATE_TODAY","Tài khoản của bạn sẽ hết hạn trong hôm nay. Hãy liên hệ với bộ phận chăm sóc khách hàng Caresoft để gia hạn tài khoản của bạn");
        hashMap.put("_comments","END");
        hashMap.put("_comments","send out");
        hashMap.put("LBL_ERR_SEND_MAIL_HEADER","<h1>Lỗi gửi email:</h1><ul>");
        hashMap.put("LBL_ERR_SEND_SMS_HEADER","<h1>Lỗi gửi SMS:</h1><ul>");
        hashMap.put("LBL_ERR_INVALID_EMAIL_TO","<li>Email gửi đi không đúng định dạng</li>");
        hashMap.put("LBL_ERR_EMPTY_TITLE","<li>Tiêu đề không được để trống</li>");
        hashMap.put("LBL_ERR_EMPTY_CONTENT","<li>Nội dung không được để trống</li>");
        hashMap.put("LBL_SEND_INBOX_FROM_COMMENT","Gửi tin nhắn cá nhân từ bình luận");
        hashMap.put("LBL_SEND_INBOX","Gửi tin nhắn cá nhân");
        hashMap.put("LBL_SEND_OTT","Gửi tin nhắn tới ứng dụng");
        hashMap.put("LBL_OTT_SERVICE","Dịch vụ OTT");
        hashMap.put("LBL_EMPTY_MESSAGE","Tin nhắn không được để trống");
        hashMap.put("LBL_SEND_INBOX_SUCCESS","Gửi tin nhắn thành công");
        hashMap.put("LBL_NOT_CHOOSE_PAGE","Page gửi đi chưa được chọn");
        hashMap.put("LBL_NOT_CHOOSE_SERVICE","Dịch vụ chưa được chọn");
        hashMap.put("LBL_MENU_ITEM_ADD_BLACKLIST","Chặn");
        hashMap.put("LBL_MENU_ITEM_REMOVE_BLACKLIST","Bỏ chặn");
        hashMap.put("MESSAGE_ADD_BLACKLIST_SUCCESS","Chặn số {{phone}} thành công");
        hashMap.put("MESSAGE_ADD_BLACKLIST_FAIL","Chặn số {{phone}} không thành công");
        hashMap.put("MESSAGE_REMOVE_BLACKLIST_SUCCESS","Mở chặn số {{phone}} thành công");
        hashMap.put("MESSAGE_REMOVE_BLACKLIST_FAIL","Mở chặn số {{phone}} không thành công");
        hashMap.put("MESSAGE_SEND_EMAIL_FAIL","Gửi Email không thành công. Vui lòng thử lại sau!");
        hashMap.put("MESSAGE_SEND_SMS_FAIL","Gửi SMS không thành công. Vui lòng thử lại sau!");
        hashMap.put("MESSAGE_SEND_HELP_FAIL","Gửi yêu cầu trợ giúp không thành công. Vui lòng thử lại sau!");
        hashMap.put("LBL_SENDING","Đang gửi...");
        hashMap.put("LBL_AZ_USER","Mã OTT");
        hashMap.put("LBL_CALL_TO_AZ","Gọi");
        hashMap.put("LBL_MESSAGE_TO_AZ","Gửi tin nhắn");
        hashMap.put("LBL_TICKET_SOURCE_VOICE","Thoại");
        hashMap.put("LBL_TICKET_SOURCE_CHAT","Chat");
        hashMap.put("LBL_TICKET_SOURCE_WEB","Web");
        hashMap.put("LBL_TICKET_SOURCE_EMAIL","Email");
        hashMap.put("LBL_TICKET_SOURCE_FACEBOOK","Facebook");
        hashMap.put("LBL_TICKET_SOURCE_VOICEMAIL","Voicemail");
        hashMap.put("LBL_TICKET_TYPE_OTHER","Khác");
        hashMap.put("LBL_FORGET_PASSWORD","Quên mật khẩu");
        hashMap.put("BTN_RESET_PASSWORD","Gửi");
        hashMap.put("LBL_RESET_GUIDE_1","Để lấy lại mật khẩu cho tài khoản");
        hashMap.put("LBL_RESET_GUIDE_2","); nhập email của bạn và chúng tôi sẽ gửi mail hướng dẫn cho bạn");
        hashMap.put("LBL_CHANGE_PASSWORD_SUCCESS","Reset mật khẩu thành công. Kiểm tra email của bạn để nhận mật khẩu mới");
        hashMap.put("LBL_EMAIL_CHANGE_PWD_NOT_FOUND","Email bạn nhập không của agent nào thuộc tài khoản này");

        hashMap.put("LBL_FACEBOOK_TITLE","CS Facebook");
        hashMap.put("LBL_REPLY_MESSAGE","Tin nhắn phản hồi");
        hashMap.put("LBL_CHAT_UPLOAD_ERR_EXTENSION","Chỉ có thể gửi ảnh tới Facebook");
        hashMap.put("LBL_NOT_CHOOSE_FB_CONV","Bạn đang không chọn hội thoại nào");
        hashMap.put("LBL_OPEN_IN_TICKET","Mở phiếu ghi");
        hashMap.put("LBL_OPEN_IN_FACEBOOK","Mở Facebook");
        hashMap.put("LBL_SHOW_COMMENT","Ẩn bình luận");
        hashMap.put("LBL_DELETE_COMMENT","Xóa bình luận");
        hashMap.put("LBL_SEND_PRIVATE_MESSAGE","Gửi tin nhắn cá nhân");
        hashMap.put("LBL_OPEN_CS_CONTACT","Mở thông tin người dùng");
        hashMap.put("LBL_CLOSE_TICKET","Đóng phiếu");
        hashMap.put("LBL_FB_NEW_REQUEST","Bạn có yêu cầu Facebook mới");
        hashMap.put("LBL_FB_USER","Người gửi: ");
        hashMap.put("LBL_NO_FB_CONV","Bạn không có hội thoại nào");

    }
}
